(()=>{'use strict';
const $=id=>document.getElementById(id);

const e={
  names:$('names'),count:$('playerCount'),games:$('games'),courts:$('courts'),duration:$('duration'),sessionLength:$('sessionLength'),rest:$('rest'),seed:$('seed'),
  status:$('setupStatus'),generate:$('generateBtn'),shuffle:$('shuffleBtn'),rebuild:$('rebuildBtn'),schedule:$('scheduleList'),players:$('playerCards'),rankings:$('rankingsList'),
  rankTopTitle:$('rankTopTitle'),rankTopMeta:$('rankTopMeta'),rankTopMedal:$('rankTopMedal'),summary:$('summary'),sticky:$('stickyLive'),stickyGame:$('stickyGame'),stickyMatch:$('stickyMatch'),
  liveStatus:$('liveStatus'),currentNo:$('currentNo'),currentCourt:$('currentCourt'),currentTeams:$('currentTeams'),currentSit:$('currentSit'),progressText:$('progressText'),progressPct:$('progressPct'),progressBar:$('progressBar'),
  complete:$('completeBtn'),next:$('nextBtn'),upNext:$('upNextList'),remaining:$('remaining'),sheet:$('sheet'),sheetContent:$('sheetContent'),theme:$('themeBtn')
};

let state=blank();
let finalRankingsShown=false;

function blank(){return{names:[],active:[],games:[],done:new Set(),results:{},locked:new Set(),score:0,config:{},sessionCode:''}}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function titleCaseName(value){return String(value??'').trim().toLocaleLowerCase().replace(/(^|[\s'-])([a-zà-ÿ])/g,(_,p,c)=>p+c.toLocaleUpperCase())}
function normalizeNames(value){return String(value??'').split(/\r?\n/).map(titleCaseName).filter(Boolean).join('\n')}
function parse(){const seen=new Map(),out=[];for(const raw of (e.names?.value||'').split(/\r?\n/)){const base=titleCaseName(raw);if(!base)continue;const key=base.toLocaleLowerCase(),n=(seen.get(key)||0)+1;seen.set(key,n);out.push(n===1?base:`${base} (${n})`)}return out}
function nm(id){return state.names[id-1]||`Player ${id}`}
function status(message,kind=''){if(e.status){e.status.textContent=message;e.status.className=`status ${kind}`}}
function count(){if(e.count)e.count.textContent=parse().length}
function cfg(){const names=parse();let per=Number.parseInt(e.games?.value||'',10);if(!Number.isFinite(per)||per<1){per=Math.min(6,Math.max(1,names.length-1));while(per>1&&(names.length*per)%4)per--}return{names,per,courts:Math.max(1,Math.min(6,Number(e.courts?.value)||1)),duration:Math.max(1,Number(e.duration?.value)||15),sessionLength:Math.max(0,Number(e.sessionLength?.value)||0),rest:e.rest?.value||'balanced',seed:Date.now()^Math.floor(Math.random()*0xffffffff)}}
function validate(c){if(c.names.length<5||c.names.length>24)return'Enter between 5 and 24 players.';if(c.per>c.names.length-1)return`Games per player cannot exceed ${c.names.length-1} with unique partners.`;if((c.names.length*c.per)%4!==0)return`${c.names.length} × ${c.per} does not divide into groups of four. Choose a different games/player value.`;if(c.sessionLength){const mins=(c.names.length*c.per/4/c.courts)*c.duration;if(mins>c.sessionLength)return`This rotation needs about ${Math.ceil(mins)} minutes, above your target.`}return''}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function makeCode(names){let h=2166136261;for(const ch of names.join('|')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return`CRG-${(h>>>0).toString(36).toUpperCase().slice(0,7)}`}
function generate(options={}){
  const stayOnView=options.stayOnView||'liveView';
  const c=cfg(),err=validate(c);
  if(err){status(err,'err');return false}
  if(!window.RotationScheduler?.generate){status('Scheduler failed to load. Refresh the page and try again.','err');return false}
  e.generate.disabled=true;if(e.shuffle)e.shuffle.disabled=true;
  if(e.shuffle&&stayOnView==='scheduleView'){e.shuffle.classList.add('is-working');e.shuffle.setAttribute('aria-busy','true');e.shuffle.textContent='Rebalancing…'}
  status('Generating and scoring the fairest rotation…');
  window.setTimeout(()=>{
    try{
      const r=window.RotationScheduler.generate({players:c.names.map((_,i)=>i+1),targets:new Map(c.names.map((_,i)=>[i+1,c.per])),per:c.per,courts:c.courts,rest:c.rest,seed:c.seed,attempts:420});
      if(!r?.games?.length)throw new Error('No valid rotation found. Try fewer games per player or add players.');
      state=blank();state.names=c.names.slice();state.active=c.names.map((_,i)=>i+1);state.games=r.games;state.score=Number(r.score)||0;state.config=c;state.sessionCode=makeCode(c.names);finalRankingsShown=false;
      e.sticky.hidden=false;view(stayOnView);render();status(`Rotation ready — ${state.games.length} games · fairness ${state.score}/100.`,'ok');
    }catch(error){console.error(error);status(error?.message||'Generation failed unexpectedly.','err')}
    finally{e.generate.disabled=false;if(e.shuffle){e.shuffle.disabled=false;e.shuffle.classList.remove('is-working');e.shuffle.removeAttribute('aria-busy');e.shuffle.textContent='Shuffle / rebalance'}}
  },20);
  return true;
}
function liveIndex(){const i=state.games.findIndex((_,n)=>!state.done.has(n));return i<0?state.games.length:i}
function render(){renderStats();renderCurrent();renderSchedule();renderPlayers();renderRankings();renderSummary()}
function renderStats(){const total=state.games.length,done=state.done.size,p=total?Math.round(done/total*100):0;e.progressText.textContent=`${done} / ${total} games`;e.progressPct.textContent=`${p}%`;e.progressBar.style.width=`${p}%`;e.remaining.textContent=`${Math.max(0,total-done-1)} remaining`}
function renderCurrent(){const i=liveIndex();if(i>=state.games.length){e.currentNo.textContent='✓ SESSION COMPLETE';e.currentCourt.textContent='COURT —';e.currentTeams.innerHTML='<div class="team">All games</div><div class="versus">DONE</div><div class="team">Great session</div>';e.currentSit.textContent='All scheduled games are complete.';e.complete.disabled=true;e.next.disabled=true;e.upNext.innerHTML='<div class="hint">No games remaining.</div>';e.stickyGame.textContent='SESSION COMPLETE';e.stickyMatch.textContent='All games finished';showFinalRankings();return}const g=state.games[i],a=g.teams[0],b=g.teams[1];e.currentNo.textContent=`GAME ${i+1}`;e.currentCourt.textContent=`COURT ${g.court||1}`;e.currentTeams.innerHTML=`<div class="team">${esc(nm(a[0]))} + ${esc(nm(a[1]))}</div><div class="versus">VS</div><div class="team">${esc(nm(b[0]))} + ${esc(nm(b[1]))}</div>`;e.currentSit.textContent=`Sitting out: ${(g.sitting||[]).length?(g.sitting||[]).map(nm).map(esc).join(', '):'None'}`;e.liveStatus.textContent=Object.prototype.hasOwnProperty.call(state.results,i)?(state.results[i]===0?'TEAM A WON':'TEAM B WON'):'NEXT UP';e.complete.disabled=false;e.next.disabled=false;e.stickyGame.textContent=`GAME ${i+1} / ${state.games.length}`;e.stickyMatch.textContent=`${nm(a[0])} + ${nm(a[1])} vs ${nm(b[0])} + ${nm(b[1])}`;const upcoming=state.games.slice(i+1,i+4);e.upNext.innerHTML=upcoming.length?upcoming.map((g2,j)=>`<div class="next-item"><span>G${i+2+j}</span><span>${esc(nm(g2.teams[0][0]))} + ${esc(nm(g2.teams[0][1]))} vs ${esc(nm(g2.teams[1][0]))} + ${esc(nm(g2.teams[1][1]))}</span></div>`).join(''):'<div class="hint">Last scheduled game.</div>'}
function renderSchedule(){if(!state.games.length){e.schedule.innerHTML='<div class="empty">Generate a rotation to see the schedule.</div>';return}e.schedule.innerHTML=state.games.map((g,i)=>{const a=g.teams[0],b=g.teams[1],done=state.done.has(i),locked=state.locked.has(i),r=state.results[i];return`<article class="game-row ${done?'done':''} ${locked?'locked':''}"><div class="game-label">G${i+1}</div><div><div class="game-match">${esc(nm(a[0]))} + ${esc(nm(a[1]))}<br><span class="hint">VS</span><br>${esc(nm(b[0]))} + ${esc(nm(b[1]))}</div><div class="hint">Court ${g.court||1} · Sitting: ${(g.sitting||[]).length?(g.sitting||[]).map(nm).map(esc).join(', '):'None'}</div></div><div><div class="game-status">${r===0?'🏆 Team A won':r===1?'🏆 Team B won':done?'Completed':locked?'Locked':'Upcoming'}</div><div class="game-actions"><button class="icon-btn" data-result="${i}">${done?'↩ Result':'✓ Result'}</button><button class="icon-btn ${locked?'active':''}" data-lock="${i}">${locked?'🔓 Unlock':'🔒 Lock'}</button></div></div></article>`}).join('');e.schedule.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>chooseWinner(Number(b.dataset.result))));e.schedule.querySelectorAll('[data-lock]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.lock);state.locked.has(i)?state.locked.delete(i):state.locked.add(i);renderSchedule()}))}
function metrics(){const m={};for(let i=1;i<=state.names.length;i++)m[i]={games:0,sits:0,wins:0,losses:0,partners:new Set(),opponents:new Set()};state.games.forEach(g=>{const[a,b]=g.teams;[...a,...b].forEach(p=>m[p]&&m[p].games++);(g.sitting||[]).forEach(p=>m[p]&&m[p].sits++);a.forEach(p=>b.forEach(q=>{m[p]?.opponents.add(nm(q));m[q]?.opponents.add(nm(p))}));[a,b].forEach(t=>t.forEach(p=>t.forEach(q=>{if(p!==q)m[p]?.partners.add(nm(q))})))});Object.entries(state.results).forEach(([k,r])=>{const g=state.games[Number(k)];if(!g)return;g.teams[r].forEach(p=>m[p].wins++);g.teams[1-r].forEach(p=>m[p].losses++)});return m}
function getRankingRows(){const m=metrics();return state.names.map((name,i)=>{const x=m[i+1],gp=x.wins+x.losses;return{name,w:x.wins,l:x.losses,g:gp,pct:gp?Math.round(x.wins/gp*100):0}}).sort((a,b)=>b.w-a.w||b.pct-a.pct||b.g-a.g||a.name.localeCompare(b.name))}
function renderPlayers(){if(!state.names.length){e.players.innerHTML='<div class="empty">No players yet.</div>';return}const m=metrics();e.players.innerHTML=state.names.map((name,i)=>{const x=m[i+1],wp=x.games?Math.round(x.wins/x.games*100):0;return`<article class="player-card"><div class="player-card-head"><h3>${esc(name)}</h3><span>${wp}% win</span></div><div class="player-meta"><span class="stat-chip">🎾 ${x.games}G</span><span class="stat-chip">🏆 ${x.wins}W</span><span class="stat-chip">✕ ${x.losses}L</span><span class="stat-chip">🪑 ${x.sits}</span></div><label class="toggle"><input type="checkbox" data-active="${i+1}" ${state.active.includes(i+1)?'checked':''}> Available</label><div class="player-links"><b>Partners:</b> ${[...x.partners].map(esc).join(', ')||'—'}<br><b>Opponents:</b> ${[...x.opponents].map(esc).join(', ')||'—'}</div></article>`}).join('');e.players.querySelectorAll('[data-active]').forEach(c=>c.addEventListener('change',()=>{const id=Number(c.dataset.active);state.active=c.checked?[...new Set([...state.active,id])]:state.active.filter(x=>x!==id);status(`${nm(id)} is ${c.checked?'available':'unavailable'}. Rebuild remaining to apply the change.`,'ok')}))}
function renderRankings(){if(!e.rankings)return;const rows=getRankingRows(),top=rows.find(r=>r.g);e.rankTopTitle.textContent=top?`${top.name} · ${top.w}-${top.l}`:'No results yet';e.rankTopMeta.textContent=top?`${top.pct}% win rate · ranked #1`:'Complete games and record a winner to build the standings.';e.rankTopMedal.textContent=top?'🏆':'🏁';e.rankings.innerHTML=rows.map((r,i)=>`<article class="rank-row"><div class="rank-pos">${r.g?`#${i+1}`:'—'}</div><div><div class="rank-name">${esc(r.name)}</div><div class="rank-record"><span class="rank-chip">${r.w}W</span><span class="rank-chip">${r.l}L</span><span class="rank-chip">${r.g} games</span></div></div><div class="rank-pct">${r.g?`${r.pct}%`:'—'}<div class="rank-muted">win rate</div></div></article>`).join('');return rows}
function renderSummary(){if(!e.summary)return;const complete=state.games.length>0&&state.done.size===state.games.length,m=metrics(),s=Object.values(m).map(x=>x.sits),spread=s.length?Math.max(...s)-Math.min(...s):0;e.summary.innerHTML=`<div class="summary-line"><span>Session code</span><b>${esc(state.sessionCode||'—')}</b></div><div class="summary-line"><span>Games</span><b>${state.games.length}</b></div><div class="summary-line"><span>Players</span><b>${state.names.length}</b></div><div class="summary-line"><span>Courts</span><b>${state.config.courts||1}</b></div><div class="summary-line"><span>Fairness</span><b>${state.score}/100</b></div><div class="summary-line"><span>Sit-out spread</span><b>${spread} game(s)</b></div><div class="summary-line"><span>Status</span><b>${complete?'SESSION COMPLETE':'In progress'}</b></div>`;$('sessionCodeText').textContent=state.sessionCode?`Session code: ${state.sessionCode}`:'No active session'}
function openSheet(html,kind=''){e.sheetContent.innerHTML=html;e.sheet.classList.remove('final-rankings');if(kind)e.sheet.classList.add(kind);e.sheet.hidden=false;e.sheet.classList.add('modal-open');document.body.classList.add('modal-open')}
function closeSheet(){e.sheet.hidden=true;e.sheet.classList.remove('modal-open','final-rankings');document.body.classList.remove('modal-open')}
function confirmAction(title,message,actionLabel,action){openSheet(`<div class="sheet-title">${esc(title)}</div><p class="hint">${esc(message)}</p><div class="confirm-actions"><button type="button" class="btn modal-cancel" id="modalCancel">Cancel</button><button type="button" class="btn modal-confirm" id="modalConfirm">${esc(actionLabel)}</button></div>`);$('modalCancel')?.addEventListener('click',closeSheet,{once:true});$('modalConfirm')?.addEventListener('click',()=>{closeSheet();action()},{once:true})}
function chooseWinner(i){const g=state.games[i];if(!g)return;const[a,b]=g.teams;openSheet(`<div class="sheet-title">Game ${i+1} result</div><p class="hint">Choose the winning team. Rankings update immediately.</p><div class="winner-grid"><button class="btn full" data-winner="0">🏆 ${esc(nm(a[0]))} + ${esc(nm(a[1]))}</button><button class="btn full" data-winner="1">🏆 ${esc(nm(b[0]))} + ${esc(nm(b[1]))}</button>${state.done.has(i)?'<button class="btn secondary full" data-clear-result>Clear result</button>':''}</div>`);e.sheetContent.querySelectorAll('[data-winner]').forEach(b=>b.addEventListener('click',()=>{state.results[i]=Number(b.dataset.winner);state.done.add(i);closeSheet();render();status(`Game ${i+1} recorded.`,'ok')}));const clear=e.sheetContent.querySelector('[data-clear-result]');if(clear)clear.addEventListener('click',()=>{state.done.delete(i);delete state.results[i];closeSheet();render()},{once:true})}
function rebuild(label){label=label||'Remaining rotation rebuilt';if(!state.games.length){status('Generate a rotation first.','err');return}const fixed=new Map();state.games.forEach((g,i)=>{if(state.done.has(i)||state.locked.has(i))fixed.set(i,{teams:g.teams.map(t=>t.slice()),sitting:(g.sitting||[]).slice(),court:g.court})});const targets=new Map(state.active.map(id=>[id,state.config.per]));const played=new Map(state.active.map(id=>[id,0]));fixed.forEach(g=>g.teams.flat().forEach(p=>played.set(p,(played.get(p)||0)+1)));state.active.forEach(id=>targets.set(id,Math.max(0,state.config.per-(played.get(id)||0))));const remaining=state.games.length-fixed.size,slots=[...targets.values()].reduce((a,b)=>a+b,0);if(slots!==remaining*4){status('Cannot rebalance with the current locked/completed games and availability. Unlock a game or add a player.','err');return}const r=window.RotationScheduler.generate({players:state.active,targets,totalGames:state.games.length,courts:state.config.courts,rest:state.config.rest,seed:Date.now(),fixed,attempts:420});if(!r?.games){status('Rebalance failed. Unlock a game or add an available player.','err');return}state.games=r.games;state.score=r.score;finalRankingsShown=false;render();status(`${label}; ${fixed.size} locked/completed game${fixed.size===1?'':'s'} kept in place.`,'ok')}
function restart(){confirmAction('Restart live session','This will clear completed game results and start the live session again.','Restart',()=>{state.done=new Set();state.results={};finalRankingsShown=false;view('liveView');render();status('Live session restarted.','ok')})}
function reset(){confirmAction('Reset everything','This will clear the current rotation, results, and player list. Continue?','Reset',()=>{state=blank();e.names.value='';e.games.value='';e.courts.value='1';e.duration.value='15';e.sessionLength.value='';count();finalRankingsShown=false;e.sticky.hidden=true;view('setupView');render();status('Everything reset.','ok')})}
function showFinalRankings(){if(finalRankingsShown)return;const ranking=getRankingRows();if(!ranking.length)return;finalRankingsShown=true;const ordinal=n=>{const j=n%10,k=n%100;return j===1&&k!==11?'st':j===2&&k!==12?'nd':j===3&&k!==13?'rd':'th'};const html=`<div class="sheet-title">Session complete</div><p class="hint">Final rankings</p><div class="completion-rankings-wrap"><div class="complete-rankings">${ranking.map((p,i)=>`<div class="complete-rank-row ${i<5?'top-five':''} ${i===0?'first-place':''}"><div class="complete-place">${i===0?'🏆 ':''}${i+1}${ordinal(i+1)}</div><div class="complete-name">${esc(p.name)}</div><div class="complete-stats"><span class="complete-wins">${p.w}W</span><span class="complete-losses">${p.l}L</span><span class="complete-games-played">${p.g} games</span></div></div>`).join('')}</div></div><button type="button" class="btn full complete-close" id="completeCloseBtn">Close rankings</button>`;openSheet(html,'final-rankings');$('completeCloseBtn')?.addEventListener('click',closeSheet,{once:true})}
function theme(){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('crg-theme',next);e.theme.textContent=next==='dark'?'☀ Light':'☾ Dark'}
function initTheme(){const t=localStorage.getItem('crg-theme')||'dark';document.documentElement.dataset.theme=t;e.theme.textContent=t==='dark'?'☀ Light':'☾ Dark';document.documentElement.classList.add('large-text')}
function courtMode(){document.body.classList.toggle('court-mode');$('courtModeBtn').textContent=document.body.classList.contains('court-mode')?'✕ Exit court mode':'☀ Court mode'}
function currentText(){const i=liveIndex();if(i>=state.games.length)return'Session complete.';const[a,b]=state.games[i].teams;return`GAME ${i+1} · COURT ${state.games[i].court||1}\n${nm(a[0])} + ${nm(a[1])}\nVS\n${nm(b[0])} + ${nm(b[1])}\nSitting out: ${(state.games[i].sitting||[]).map(nm).join(', ')||'None'}`}
function allText(){return state.games.map((g,i)=>{const[a,b]=g.teams;return`GAME ${i+1} · COURT ${g.court||1}\n${nm(a[0])} + ${nm(a[1])}\nVS\n${nm(b[0])} + ${nm(b[1])}\nSitting out: ${(g.sitting||[]).map(nm).join(', ')||'None'}`}).join('\n\n')}
async function share(text,title){if(navigator.share){try{await navigator.share({title,text})}catch{}}else if(navigator.clipboard)await navigator.clipboard.writeText(text)}
function csv(){const rows=[['Game','Court','Team A','Team B','Sitting Out','Result']];state.games.forEach((g,i)=>{const[a,b]=g.teams;rows.push([i+1,g.court||1,`${nm(a[0])} + ${nm(a[1])}`,`${nm(b[0])} + ${nm(b[1])}`,(g.sitting||[]).map(nm).join(' | ')||'None',state.results[i]===0?'Team A won':state.results[i]===1?'Team B won':''])});const text=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='court-rotation.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function bind(){
  e.generate?.addEventListener('click',()=>generate());
  e.names?.addEventListener('input',count);
  e.names?.addEventListener('paste',()=>window.setTimeout(()=>{e.names.value=normalizeNames(e.names.value);count()},0));
  $('addPlayerBtn')?.addEventListener('click',()=>{e.names.value+=(e.names.value.trim()?'\n':'')+'New Player';count();e.names.focus()});
  $('clearNamesBtn')?.addEventListener('click',()=>{e.names.value='';count();e.names.focus()});
  $('pasteBtn')?.addEventListener('click',()=>{openSheet(`<div class="sheet-title">Paste names</div><textarea id="sheetPaste" class="sheet-copy" placeholder="One player per line"></textarea><button class="btn full" id="usePaste">Use names</button>`);const input=$('sheetPaste');input?.addEventListener('paste',()=>window.setTimeout(()=>{input.value=normalizeNames(input.value)},0));input?.focus();$('usePaste')?.addEventListener('click',()=>{e.names.value=normalizeNames(input?.value||'');count();closeSheet();e.names.focus()},{once:true})});
  e.shuffle?.addEventListener('click',()=>{
    if(!state.games.length){generate({stayOnView:'scheduleView'});return}
    if(e.shuffle){e.shuffle.disabled=true;e.shuffle.classList.add('is-working');e.shuffle.setAttribute('aria-busy','true');e.shuffle.textContent='Rebalancing…'}
    window.setTimeout(()=>{
      rebuild('Shuffled the remaining games');
      if(e.shuffle){e.shuffle.disabled=false;e.shuffle.classList.remove('is-working');e.shuffle.removeAttribute('aria-busy');e.shuffle.textContent='Shuffle / rebalance'}
    },20);
  });
  e.rebuild?.addEventListener('click',()=>rebuild());
  e.theme?.addEventListener('click',theme);
  $('courtModeBtn')?.addEventListener('click',courtMode);
  e.complete?.addEventListener('click',()=>chooseWinner(liveIndex()));
  e.next?.addEventListener('click',()=>{const i=liveIndex();if(i<state.games.length-1){state.done.add(i);render()}});
  $('copyCurrentBtn')?.addEventListener('click',()=>share(currentText(),'Current court game'));
  $('shareCurrentBtn')?.addEventListener('click',()=>share(currentText(),'Current court game'));
  $('qrBtn')?.addEventListener('click',()=>openSheet('<div class="sheet-title">QR snapshot</div><p class="hint">Use Share current for a direct share. QR snapshots are intentionally kept external to avoid breaking offline use.</p>'));
  $('copyAllBtn')?.addEventListener('click',()=>share(allText(),'Court rotation session'));
  $('shareSessionBtn')?.addEventListener('click',()=>share(allText(),'Court rotation session'));
  $('csvBtn')?.addEventListener('click',csv);
  $('printBtn')?.addEventListener('click',()=>window.print());
  $('restartBtn')?.addEventListener('click',restart);
  $('resetBtn')?.addEventListener('click',reset);
  $('highContrastBtn')?.addEventListener('click',()=>{document.body.classList.toggle('high-contrast');$('highContrastBtn').textContent=`High contrast: ${document.body.classList.contains('high-contrast')?'On':'Off'}`});
  $('largeTextBtn')?.addEventListener('click',()=>{document.documentElement.classList.toggle('large-text');$('largeTextBtn').textContent=`Large text: ${document.documentElement.classList.contains('large-text')?'On':'Off'}`});
  $('sheetClose')?.addEventListener('click',closeSheet);
  $('sheetBackdrop')?.addEventListener('click',e2=>{if(e2.target===$('sheetBackdrop'))closeSheet()});
  document.addEventListener('keydown',e2=>{if(e2.key==='Escape'&&!e.sheet.hidden)closeSheet()});
  document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
}

bind();initTheme();count();render();
})();
