(()=>{'use strict';
const KEY='crg-session-v4',PROFILE_KEY='crg-player-profiles-v1',GAMING_KEY='crg-gamification-v1';
const $=id=>document.getElementById(id),names=$('names'),courts=$('courts'),duration=$('duration'),sessionLength=$('sessionLength'),generate=$('generateBtn');
if(!names||!generate)return;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const title=v=>String(v||'').trim().toLocaleLowerCase().replace(/(^|[\s'-])([a-zà-ÿ])/g,(_,p,c)=>p+c.toLocaleUpperCase());
const parseNames=()=>names.value.split(/\r?\n/).map(title).filter(Boolean);
const read=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??d}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let skills=read('crg-skills-v1',{}),db=read(GAMING_KEY,{matches:[],season:{name:'Open Season',startedAt:Date.now()},players:{}});
function profile(n){if(!db.players[n])db.players[n]={rating:1200,games:0,wins:0,losses:0,streak:0,bestStreak:0,partners:{},achievements:[],seasonGames:0,seasonWins:0};return db.players[n]}
function persist(){write(GAMING_KEY,db)}
function button(label,id,cls='btn secondary'){const b=document.createElement('button');b.id=id;b.type='button';b.className=cls;b.textContent=label;return b}
function removePlayer(n){const next=parseNames().filter(x=>x!==n);names.value=next.join('\n');delete skills[n];write('crg-skills-v1',skills);renderSkills();saveDraft()}
function renderSkills(){const rows=$('skillRows');if(!rows)return;const ns=parseNames();rows.innerHTML=ns.length?ns.map(n=>{const v=skills[n]||'Intermediate';return `<div class="skill-row"><span class="skill-player">${esc(n)}</span><select data-skill="${esc(n)}" aria-label="Skill level for ${esc(n)}"><option${v==='Beginner'?' selected':''}>Beginner</option><option${v==='Intermediate'?' selected':''}>Intermediate</option><option${v==='Advanced'?' selected':''}>Advanced</option></select><button type="button" class="btn ghost skill-remove" data-remove-player="${esc(n)}" aria-label="Remove ${esc(n)}">Remove</button></div>`}).join(''):'<div class="hint">Add player names to set levels.</div>';rows.querySelectorAll('[data-skill]').forEach(s=>s.addEventListener('change',()=>{skills[s.dataset.skill]=s.value;write('crg-skills-v1',skills);saveDraft()}));rows.querySelectorAll('[data-remove-player]').forEach(b=>b.addEventListener('click',()=>removePlayer(b.dataset.removePlayer)))}
function installSkills(){if($('skillSetup'))return;const host=names.closest('.card');if(!host)return;host.classList.add('players-skill-card');const pane=document.createElement('div');pane.className='player-pane';while(host.firstChild)pane.appendChild(host.firstChild);const box=document.createElement('div');box.id='skillSetup';box.className='skill-pane';box.innerHTML='<div class="card-head"><h3>Skill levels</h3><span class="count">Optional</span></div><p class="hint">Set each player level for fairer team balancing.</p><div id="skillRows" class="tool-stack"></div>';host.append(pane,box);renderSkills();names.addEventListener('input',()=>{renderSkills();saveDraft()},{passive:true})}
function draft(){return{names:parseNames(),courts:courts?.value||'1',duration:duration?.value||'15',sessionLength:sessionLength?.value||'',skills,updatedAt:Date.now()}}
function saveDraft(){write(KEY,draft());persist()}
function installSession(){const card=[...document.querySelectorAll('#moreView .card')][0],stack=card?.querySelector('.tool-stack');if(!stack||$('resumeBtn'))return;const resume=button('Resume last session','resumeBtn'),save=button('Save session','saveSessionBtn'),share=button('Share display view','shareDisplayBtn');stack.prepend(resume,save,share);const note=document.createElement('p');note.id='resumeNote';note.className='hint';stack.after(note);const refresh=()=>{const d=read(KEY,null);note.textContent=d?`Saved ${d.names.length} players · ${new Date(d.updatedAt).toLocaleString()}`:'No saved session yet';resume.disabled=!d};save.onclick=()=>{saveDraft();refresh();toast('Session saved locally')};resume.onclick=()=>{const d=read(KEY,null);if(!d)return;names.value=d.names.join('\n');if(courts)courts.value=d.courts;if(duration)duration.value=d.duration;if(sessionLength)sessionLength.value=d.sessionLength||'';skills=d.skills||{};renderSkills();generate.click()};share.onclick=shareReadOnly;refresh()}
function offline(){let b=$('offlineBadge');if(!b){b=document.createElement('div');b.id='offlineBadge';b.textContent='';document.body.appendChild(b)}const set=()=>b.textContent=navigator.onLine?'● Online · saved locally':'● Offline · working locally';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});set();addEventListener('online',set);addEventListener('offline',set)}
function schedule(){return [...document.querySelectorAll('#scheduleList .game-row')].map((r,i)=>{const txt=r.querySelector('.game-match')?.innerText||'',lines=txt.split(/\n/).filter(Boolean),vs=lines.findIndex(x=>x.trim().toUpperCase()==='VS');if(vs>0)return{index:i,teams:[lines[vs-1].split(' + ').map(s=>s.trim()),lines[vs+1]?.split(' + ').map(s=>s.trim())||[]]};return null}).filter(g=>g?.teams?.[1]?.length)}
function updateRating(i,winner){const g=schedule()[i];if(!g)return;const A=g.teams[0].map(title),B=g.teams[1].map(title),avg=t=>t.reduce((s,n)=>s+profile(n).rating,0)/t.length,ra=avg(A),rb=avg(B),ea=1/(1+10**((rb-ra)/400)),eb=1-ea,k=24,ca=Math.round(k*((winner===0?1:0)-ea)),cb=Math.round(k*((winner===1?1:0)-eb)),win=winner===0?A:B,lose=winner===0?B:A;win.forEach(n=>{const p=profile(n);p.rating=Math.max(400,p.rating+(winner===0?ca:cb));p.games++;p.wins++;p.streak++;p.bestStreak=Math.max(p.bestStreak,p.streak);p.seasonGames=(p.seasonGames||0)+1;p.seasonWins=(p.seasonWins||0)+1});lose.forEach(n=>{const p=profile(n);p.rating=Math.max(400,p.rating+(winner===0?cb:ca));p.games++;p.losses++;p.streak=0;p.seasonGames=(p.seasonGames||0)+1});[A,B].forEach(t=>t.forEach(n=>{const p=profile(n);t.filter(q=>q!==n).forEach(q=>p.partners[q]=(p.partners[q]||0)+1)}));db.matches.push({at:Date.now(),game:i,winner,teams:[A,B]});db.matches=db.matches.slice(-1000);achievements();persist();renderGaming()}
function achievements(){const now=Date.now(),week=now-7*86400000;Object.entries(db.players).forEach(([n,p])=>{const add=a=>{if(!p.achievements.includes(a))p.achievements.push(a)};if(p.streak>=5)add('Unstoppable');if(p.games>=50)add('Iron Player');if(Math.max(0,...Object.values(p.partners||{}))>=10)add('Best Partners');const wm=db.matches.filter(m=>m.at>=week&&m.teams.flat().includes(n));if(wm.length&&wm.every(m=>(m.winner===0?m.teams[0]:m.teams[1]).includes(n)))add('Perfect Week')})}
function season(){return db.season?.name||'Open Season'}
function newSeason(){const n=prompt('Season name:','Spring Smash');if(!n)return;db.season={name:title(n),startedAt:Date.now()};Object.values(db.players).forEach(p=>{p.seasonGames=0;p.seasonWins=0});persist();renderGaming();toast('New season started')}
function renderGaming(){}
function toast(msg){let t=$('crgToast');if(!t){t=document.createElement('div');t.id='crgToast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1600)}
function shareReadOnly(){const g=schedule();if(!g.length)return toast('Generate a session first');const data={season:season(),games:g.slice(0,8),ratings:Object.entries(db.players).map(([name,p])=>({name,rating:p.rating||1200}))};const payload=btoa(unescape(encodeURIComponent(JSON.stringify(data))));const url=`${location.origin}${location.pathname}#spectator=${payload}`;if(navigator.share)navigator.share({title:'Court Rotation Display',url}).catch(()=>{});else navigator.clipboard?.writeText(url).then(()=>toast('Display link copied'))}
function spectator(){if(!location.hash.startsWith('#spectator='))return;try{const d=JSON.parse(decodeURIComponent(escape(atob(location.hash.slice(11)))));document.body.classList.add('spectator-mode');const app=document.querySelector('.app');if(app)app.innerHTML=`<main style="max-width:1200px;margin:0 auto;padding:24px"><div class="card"><span class="eyebrow">COURT DISPLAY</span><h1 style="font-size:clamp(42px,7vw,86px)">${esc(d.season)}</h1><div style="display:grid;gap:12px">${d.games.map((g,i)=>`<div class="card"><div class="eyebrow">GAME ${i+1}</div><div style="font-size:clamp(24px,4vw,52px);font-weight:900">${g.teams[0].map(esc).join(' + ')} <span class="hint">VS</span> ${g.teams[1].map(esc).join(' + ')}</div></div>`).join('')}</div><div class="card"><h2>Leaderboard</h2>${d.ratings.sort((a,b)=>b.rating-a.rating).map((r,i)=>`<div class="rank-row"><div class="rank-pos">#${i+1}</div><div class="rank-name">${esc(r.name)}</div><div class="rank-pct">${r.rating}</div></div>`).join('')}</div></div></main>`}catch{}}
function results(){}
installSkills();installSession();spectator();
const s=document.createElement('script');s.src='./player-ui.js?v=crg1';document.body.appendChild(s);
})();
