(()=>{'use strict';
const CONFIG=window.CRG_SUPABASE_CONFIG||{},TABLE='court_rotation_sessions',HOST_KEY='crg-supabase-host-key-v1',POLL_MS=4000;
const ERRORS=window.CRG_LIVE_SYNC_ERRORS||Object.freeze({INVALID_SESSION_CODE:'Invalid session code.',INVALID_HOST_KEY:'Invalid host key.',INVALID_HOST_KEY_OR_EXPIRED:'Invalid host key or expired session.',CAPACITY_REACHED:'Capacity reached.',PAYLOAD_TOO_LARGE:'Payload too large.',PAYLOAD_REQUIRED:'Payload is required.'});window.CRG_LIVE_SYNC_ERRORS=ERRORS;
let hostClient=null,hostClientCode='',spectatorClient=null,spectatorClientCode='',hostChannel=null,spectatorChannel=null,hostCode='',spectatorCode='',publishTimer=0,pollTimer=0,retryTimer=0,retryAttempt=0,publishRetryTimer=0,publishRetryAttempt=0,publishRetryWaiting=false,connectionOnline=false,lastRenderedAt=0;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let configResolved=false;const waitConfig=async()=>{if(configResolved)return CONFIG;try{await window.CRG_SUPABASE_CONFIG_READY}catch{}configResolved=true;return CONFIG};
const configAvailable=()=>Boolean(CONFIG.url&&CONFIG.publishableKey);
const hostKeyFor=code=>{const key=HOST_KEY+':'+code;try{let v=localStorage.getItem(key);if(v)return v;const b=new Uint8Array(32);crypto.getRandomValues(b);v=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');localStorage.setItem(key,v);return v}catch{return'crg-'+code+'-'+Math.random().toString(36).slice(2)+Date.now().toString(36)}};
async function client(forHost=false,code=''){await waitConfig();if(!CONFIG.url||!CONFIG.publishableKey)return null;if(forHost&&hostClient&&hostClientCode===code)return hostClient;if(!forHost&&spectatorClient&&spectatorClientCode===code)return spectatorClient;try{if(!window.supabase?.createClient){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}if(!window.supabase?.createClient)return null;const headers={};if(code)headers['x-crg-session-code']=code;const opts=Object.keys(headers).length?{global:{headers}}:{};const c=window.supabase.createClient(CONFIG.url,CONFIG.publishableKey,opts);if(forHost){hostClient=c;hostClientCode=code}else{spectatorClient=c;spectatorClientCode=code}return c}catch(e){console.warn('CRG Supabase client failed:',e);return null}}
function sessionCode(){return($('sessionCodeText')?.textContent||'').match(/CRG-[A-Z0-9]+/)?.[0]||''}
function snapshot(){return typeof window.CRG_GET_LIVE_SNAPSHOT==='function'?window.CRG_GET_LIVE_SNAPSHOT():null}
function classifyRpcError(error){const message=String(error?.message||'');if(message===ERRORS.INVALID_HOST_KEY_OR_EXPIRED)return'renew';if(message===ERRORS.CAPACITY_REACHED)return'capacity';if(message===ERRORS.PAYLOAD_TOO_LARGE)return'payload-too-large';if(message===ERRORS.INVALID_SESSION_CODE||message===ERRORS.INVALID_HOST_KEY||message===ERRORS.PAYLOAD_REQUIRED)return'client-error';return'retry'}
async function persist(data,code){await waitConfig();if(!configAvailable())return{ok:false,kind:'config',error:new Error('Live sync is not configured.')};const sb=await client(true,code);if(!sb||typeof sb.rpc!=='function')return{ok:false,kind:'retry',error:new Error('Supabase publish RPC is unavailable.')};try{const{error}=await sb.rpc('publish_session',{p_code:code,p_host_key:hostKeyFor(code),p_payload:data});if(!error)return{ok:true};const kind=classifyRpcError(error);if(kind!=='retry')console.warn('CRG live state RPC rejected:',error);else console.warn('CRG live state RPC failed:',error);return{ok:false,kind,error}}catch(error){console.warn('CRG live state RPC request failed:',error);return{ok:false,kind:'retry',error}}
}
async function fetchState(code){const sb=await client(false,code);if(!sb||typeof sb.from!=='function')return{kind:'error',error:new Error('Supabase client unavailable.')};try{const{data,error}=await sb.from(TABLE).select('session_code,payload,updated_at,expires_at').eq('session_code',code).maybeSingle();if(error){console.warn('CRG live state read failed:',error);return{kind:'error',error}}if(!data?.payload)return{kind:'ended'};return{kind:'ok',payload:{...data.payload,updatedAt:data.payload.updatedAt||data.updated_at||new Date().toISOString()}}}catch(e){console.warn('CRG live state read failed:',e);return{kind:'error',error:e}}}
async function channel(topic,events,onStatus,code=''){const sb=await client(false,code);if(!sb?.channel)return null;return await new Promise(resolve=>{let done=false,settle=v=>{if(!done){done=true;resolve(v)}};const ch=sb.channel(topic,{config:{broadcast:{self:false}}});Object.entries(events).forEach(([name,fn])=>ch.on('broadcast',{event:name},fn));try{ch.subscribe(status=>{onStatus?.(status);if(status==='SUBSCRIBED')settle(ch);else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED')settle(null)})}catch(e){console.warn('CRG realtime subscribe failed:',e);settle(null)}setTimeout(()=>settle(null),7000)})}
async function ensureHostChannel(code){if(hostChannel&&hostCode===code)return true;if(hostChannel){try{await hostChannel.unsubscribe()}catch{}hostChannel=null}const ch=await channel('crg-session-'+code,{'request-state':()=>publish(true)},status=>{if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status))hostChannel=null},code);if(!ch)return false;hostChannel=ch;hostCode=code;return true}
function setLiveButton(mode){const b=$('copyLiveSpectatorBtn');if(!b)return;if(mode==='unavailable')b.textContent='Live sync unavailable';else if(mode==='retrying')b.textContent='Live sync unavailable · retrying';else if(mode==='error')b.textContent='Live sync error';else b.textContent='Copy live spectator link'}
function canPublishRetry(){return document.visibilityState!=='hidden'&&navigator.onLine!==false}
function resumePublishRetry(){if(publishRetryWaiting&&canPublishRetry()){publishRetryWaiting=false;publish(false)}}
function schedulePublishRetry(){window.clearTimeout(publishRetryTimer);const base=Math.min(30000,1000*2**Math.min(publishRetryAttempt,5));const jitter=0.8+Math.random()*0.4;const delay=Math.min(30000,Math.max(250,Math.round(base*jitter)));publishRetryAttempt+=1;publishRetryTimer=window.setTimeout(()=>{publishRetryTimer=0;if(!canPublishRetry()){publishRetryWaiting=true;return}publish(false)},delay)}
function removePublishFallback(){document.querySelector('.live-publish-fallback')?.remove()}
async function copyPublishFallback(){try{if(typeof window.CRG_COPY_FROZEN_SNAPSHOT_PAYLOAD==='function'){return await window.CRG_COPY_FROZEN_SNAPSHOT_PAYLOAD(snapshot())}return await copySnapshot()}catch(error){console.warn('CRG publish fallback copy failed:',error);toast('Read-only snapshot copy failed');return false}}
function showPublishFallback(){if(document.body.classList.contains('spectator-mode'))return;const anchor=$('copyLiveSpectatorBtn');if(!anchor?.parentElement)return;removePublishFallback();const wrap=document.createElement('div');wrap.className='live-publish-fallback';const p=document.createElement('p');p.className='hint';p.textContent='Live sync is unavailable. Share a read-only snapshot instead.';const b=document.createElement('button');b.type='button';b.className='btn secondary full';b.id='copyPublishFallbackBtn';b.textContent='Copy read-only snapshot';b.addEventListener('click',()=>copyPublishFallback());wrap.append(p,b);anchor.insertAdjacentElement('afterend',wrap)}
function handlePublishFailure(result){showPublishFallback();if(result.kind==='config'){setLiveButton('unavailable');toast('Live sync unavailable');return}if(result.kind==='retry'){setLiveButton('retrying');if(publishRetryAttempt===0)toast('Live sync unavailable · retrying with backoff');schedulePublishRetry();return}if(result.kind==='capacity'){setLiveButton('unavailable');toast('Live sync unavailable');return}if(result.kind==='payload-too-large'){setLiveButton('error');toast('Live sync error · payload too large');return}setLiveButton('error');console.error('CRG live sync client error:',result.error);toast('Live sync error · '+String(result.error?.message||'invalid publish request'))}
async function publish(force=false){if(!force&&(publishRetryTimer||publishRetryWaiting))return{storageReady:false,realtimeReady:false,reason:'retry-pending'};const data=snapshot(),code=data?.sessionCode||sessionCode();if(!data||!code)return{storageReady:false,realtimeReady:false};let result=await persist(data,code);if(result.kind==='renew'){const renewed=await window.CRG_RENEW_SESSION_CODE?.();if(!renewed){handlePublishFailure({kind:'client-error',error:new Error('Could not generate a new session code.')});return{storageReady:false,realtimeReady:false}}const nextCode=String(renewed);const nextData=snapshot()||{...data,sessionCode:nextCode};result=await persist(nextData,nextCode);if(!result.ok){handlePublishFailure(result);return{storageReady:false,realtimeReady:false}}toast('Live session was renewed · share the new live link.')}else if(!result.ok){handlePublishFailure(result);return{storageReady:false,realtimeReady:false}}window.clearTimeout(publishRetryTimer);publishRetryTimer=0;publishRetryWaiting=false;publishRetryAttempt=0;removePublishFallback();setLiveButton('ready');const liveData=snapshot()||data,realtimeReady=await ensureHostChannel(liveData.sessionCode||code);if(realtimeReady){try{await hostChannel.send({type:'broadcast',event:'state',payload:{...liveData,updatedAt:new Date().toISOString()}})}catch(e){console.warn('CRG realtime broadcast failed:',e)}}return{storageReady:true,realtimeReady}}
function queuePublish(){clearTimeout(publishTimer);publishTimer=setTimeout(()=>{if(!document.body.classList.contains('spectator-mode'))publish(false)},120)}
async function copyUrl(url,promptText){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(url);return true}}catch(e){console.warn('CRG copy failed:',e)}try{prompt(promptText,url);return true}catch{return false}}
function setSnapshotButton(){const b=$('copyLiveSpectatorBtn');if(b)b.textContent='Copy read-only snapshot link'}
function encodeSnapshot(d){const bytes=new TextEncoder().encode(JSON.stringify(d));let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return encodeURIComponent(btoa(bin))}
async function copySnapshot(){const d=snapshot(),code=d?.sessionCode||sessionCode();if(!code){toast('Generate a rotation first.');return false}const url=location.origin+location.pathname+'?s='+encodeSnapshot(d)+'&view=spectator';const ok=await copyUrl(url,'Copy this read-only spectator link:');if(ok)toast('Read-only snapshot link copied');return ok}
async function startHost(){const code=sessionCode()||snapshot()?.sessionCode;if(!code){toast('Generate a rotation first.');return false}const r=await publish(true);if(!r.storageReady){return false}const liveCode=snapshot()?.sessionCode||sessionCode();setLiveButton('ready');const url=location.origin+location.pathname+'?live='+encodeURIComponent(liveCode)+'&view=spectator';const ok=await copyUrl(url,'Copy this live spectator link:');if(ok)toast(r.realtimeReady?'Live spectator link copied':'Live spectator link copied · realtime reconnecting');return ok}
async function copySpectatorSnapshot(){const data=lastSpectatorPayload;if(!data?.sessionCode){toast('No read-only snapshot is available yet.');return false}try{if(typeof window.CRG_COPY_FROZEN_SNAPSHOT_PAYLOAD==='function')return await window.CRG_COPY_FROZEN_SNAPSHOT_PAYLOAD(data);const url=location.origin+location.pathname+'?s='+encodeSnapshot(data)+'&view=spectator';const ok=await copyUrl(url,'Copy this read-only spectator link:');if(ok)toast('Read-only snapshot link copied');return ok}catch(error){console.warn('CRG spectator snapshot copy failed:',error);toast('Read-only snapshot copy failed');return false}}
function removeLiveFailure(){document.querySelector('.spectator-live-failure')?.remove()}
function renderLiveFailure(message='The live session cannot be reached right now. Retrying automatically.'){document.body.classList.add('spectator-mode');const app=document.querySelector('.app');if(!app)return;const button='<button type="button" class="btn secondary" id="spectatorRetryBtn">Retry now</button>'+(lastSpectatorPayload?'<button type="button" class="btn secondary" id="spectatorSnapshotBtn">Copy read-only snapshot</button>':'');const note=lastSpectatorPayload?'The last displayed state remains on screen and can be copied as a read-only snapshot.':'No shared state has been received yet. Retry when the connection is available.';const markup='<section class="card spectator-section spectator-live-failure"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE SYNC</span><h2>Live sync unavailable</h2><p class="hint">'+esc(message)+'</p><p class="hint">'+esc(note)+'</p></div><div class="spectator-live-failure-actions">'+button+'</div></div></section>';const layout=app.querySelector('.spectator-layout')||app.querySelector('.live-leaderboard-page')?.parentElement||app.querySelector('.shared-live-page');if(layout){layout.querySelector(':scope > .spectator-live-failure')?.remove();layout.insertAdjacentHTML('afterbegin',markup)}else{app.innerHTML='<main class="shared-live-page">'+markup+'</main>'}$('spectatorRetryBtn')?.addEventListener('click',()=>{retryAttempt=0;if(!spectatorChannel)connectSpectator(spectatorCode,spectatorMode);startPolling()});$('spectatorSnapshotBtn')?.addEventListener('click',copySpectatorSnapshot)}

function toast(msg){let t=$('crgToast');if(!t){t=document.createElement('div');t.id='crgToast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2600)}
document.addEventListener('visibilitychange',resumePublishRetry);window.addEventListener('online',resumePublishRetry);
window.CRG_PUBLISH_LIVE=()=>publish(true);window.CRG_LIVE_SYNC_TOUCH=queuePublish;window.CRG_START_LIVE_SYNC=()=>publish(true);window.CRG_COPY_LIVE_SPECTATOR_LINK=startHost;window.CRG_COPY_LIVE_LINK=startHost;
let spectatorMode='',pollBusy=false,pollingPaused=false,spectatorRetryWaiting=false,lastSpectatorPayload=null;
function updateConnection(message){connectionOnline=message==='Realtime connected';document.body.dataset.spectatorConnection=connectionOnline?'online':'offline';document.querySelectorAll('.spectator-connection-status').forEach(n=>n.textContent=message)}
function renderConnecting(message='Connecting to the shared session…'){document.body.classList.add('spectator-mode');const app=document.querySelector('.app');if(!app)return;app.innerHTML='<main class="shared-live-page"><section class="card spectator-section spectator-connect-card"><span class="eyebrow">LIVE COURT DISPLAY</span><h1>Reconnecting…</h1><p class="hint">'+esc(message)+'</p><button type="button" class="btn secondary" id="spectatorRetryBtn">Retry now</button><p class="hint spectator-fallback-label"><b>Read-only snapshot fallback:</b> ask the host for the frozen snapshot link.</p></section></main>';$('spectatorRetryBtn')?.addEventListener('click',()=>{retryAttempt=0;connectSpectator(spectatorCode,spectatorMode)})}
function renderSessionEnded(){clearInterval(pollTimer);clearTimeout(retryTimer);stopSpecTimer();if(spectatorChannel){try{spectatorChannel.unsubscribe()}catch{}spectatorChannel=null}document.body.classList.add('spectator-mode');const app=document.querySelector('.app');if(!app)return;app.innerHTML='<main class="shared-live-page"><section class="card spectator-section spectator-connect-card spectator-ended"><span class="eyebrow">LIVE COURT DISPLAY</span><h1>Session ended</h1><p class="hint">This live session is no longer available. Ask the host for a new live link if the session is still running.</p></section></main>'}
function applyPayload(d,source){if(!d)return false;const t=Date.parse(d?.updatedAt||'');if(t&&t<lastRenderedAt)return false;if(t)lastRenderedAt=t;lastSpectatorPayload=d;removeLiveFailure();if(spectatorMode==='leaderboard')renderLeaderboard(d);else renderSnapshot(d);if(source==='realtime')updateConnection('Realtime connected');return true}
async function poll(){if(!spectatorCode||pollBusy||pollingPaused||document.visibilityState==='hidden')return;pollBusy=true;const result=await fetchState(spectatorCode);pollBusy=false;if(result.kind==='ok'){applyPayload(result.payload,'poll');return}if(result.kind==='ended'){renderSessionEnded();return}updateConnection('Live sync unavailable');renderLiveFailure('The shared session could not be refreshed. Retrying automatically when the connection is available.')}
function startPolling(){clearInterval(pollTimer);pollTimer=0;if(!spectatorCode||document.visibilityState==='hidden'){pollingPaused=true;return}pollingPaused=false;pollTimer=setInterval(poll,POLL_MS);poll()}
function retryConnect(){clearTimeout(retryTimer);if(!spectatorCode||document.visibilityState==='hidden'){spectatorRetryWaiting=true;return}spectatorRetryWaiting=false;const delay=Math.min(10000,1200*2**Math.min(retryAttempt++,3));retryTimer=setTimeout(()=>connectSpectator(spectatorCode,spectatorMode),delay)}
async function connectSpectator(code,mode){if(spectatorChannel){try{await spectatorChannel.unsubscribe()}catch{}spectatorChannel=null}const ch=await channel('crg-session-'+code,{'state':p=>{if(p?.payload)applyPayload(p.payload,'realtime')}},status=>{if(status==='SUBSCRIBED'){retryAttempt=0;spectatorRetryWaiting=false;updateConnection('Realtime connected')}else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status)){spectatorChannel=null;updateConnection('Live sync unavailable');renderLiveFailure('The live connection was interrupted. Retrying automatically when the connection is available.');retryConnect()}},code);if(!ch){updateConnection('Live sync unavailable');renderLiveFailure('The live connection could not be established. Retrying automatically when the connection is available.');retryConnect();return}spectatorChannel=ch}
function stopSpecTimer(){if(window.CRG_SPECTATOR_TIMER)clearInterval(window.CRG_SPECTATOR_TIMER)}
function startSpectatorTimer(cur){stopSpecTimer();const node=$('spectatorLiveTimer');if(!node||!cur?.timerRunning)return;const start=Number(cur.timerStartedAt),base=Number(cur.timerSeconds)||0;const tick=()=>node.textContent=formatElapsed(Number.isFinite(start)?Math.max(0,Math.floor((Date.now()-start)/1000)):base);tick();window.CRG_SPECTATOR_TIMER=setInterval(tick,1000)}
function startSpectatorCourtTimers(courts){stopSpecTimer();const nodes=[...document.querySelectorAll('[data-spectator-timer]')];if(!nodes.length)return;const tick=()=>nodes.forEach(node=>{if(node.dataset.running!=='true')return;const start=Number(node.dataset.startedAt),base=Number(node.dataset.base)||0;node.textContent=formatElapsed(Number.isFinite(start)?Math.max(0,Math.floor((Date.now()-start)/1000)):base)});tick();window.CRG_SPECTATOR_TIMER=setInterval(tick,1000)}
function formatElapsed(sec){const n=Math.max(0,Math.floor(Number(sec)||0));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function placeLabel(n){const j=n%10,k=n%100;return n===1?'🏆🥇 1st':n===2?'🥈 2nd':n===3?'🥉 3rd':n+(j===1&&k!==11?'st':j===2&&k!==12?'nd':j===3&&k!==13?'rd':'th')}
function resultSummaryMarkup(r){if(!r)return'';const parts=['🏆 Winner: '+(r.winnerNames||[]).join(' and ')];if(Number.isFinite(Number(r.durationSeconds)))parts.push('Won in '+formatElapsed(r.durationSeconds));if(r.score&&Number.isFinite(Number(r.score.a))&&Number.isFinite(Number(r.score.b)))parts.push((r.winner===0?r.score.a:r.score.b)+' – '+(r.winner===0?r.score.b:r.score.a));return'<p class="spectator-result-summary">'+esc(parts.join(' · '))+'</p>'}
function renderSnapshot(d){
document.body.classList.add('spectator-mode');
const app=document.querySelector('.app');
if(!app)return;
const current=d.current||{},p=d.progress||{},r=window.CRG_TEAM_RENDERER;
const currentTeams=current.teams?.flat()?.length?current.teams:(d.schedule?.[Number(current.index)]?.teams||[]);
const completed=Number(p.completed)||0,total=Number(p.total)||Number(d.schedule?.length)||0;
const progress=Number.isFinite(Number(p.percent))?Math.max(0,Math.min(100,Number(p.percent))):total?Math.round(completed/total*100):0;
const match=g=>r.renderMatchup(g?.teams||[],{variant:'spectator'});
const games=(d.schedule||[]).map(g=>'<article class="card spectator-section spectator-game"><div class="eyebrow">GAME '+esc(g.index)+' · COURT '+esc(g.court||1)+'</div>'+match(g)+(g.done&&g.result?resultSummaryMarkup(g.result):'<p class="hint">Upcoming</p>')+'</article>').join('');
const activeGameNos=new Set(Array.isArray(d.courts)&&d.courts.length>1?d.courts.map(c=>Number(c.gameNo)).filter(Number.isFinite):[]);
const upNextSource=Array.isArray(d.courts)&&d.courts.length>1
  ? (d.schedule||[]).filter(g=>!g.done&&!activeGameNos.has(Number(g.index))).slice(0,4)
  : (d.upNext||[]);
const up=upNextSource.map(g=>'<article class="spectator-upnext-row"><b>GAME '+esc(g.index||'')+'</b>'+r.renderMatchup(g.teams,{variant:'spectator',className:'spectator-upnext-matchup'})+'</article>').join('');
const log=(d.matchLog||[]).map(g=>'<article class="spectator-log-row"><div class="spectator-log-head"><b>GAME '+esc(g.index||'')+'</b><span>COURT '+esc(g.court||1)+'</span></div>'+r.renderMatchup(g.teams,{variant:'spectator',className:'spectator-log-matchup'})+(g.result?resultSummaryMarkup(g.result):'')+'</article>').join('');
const ranks=(d.rankings||[]).map(x=>'<div class="rank-row"><div class="rank-pos">'+(x.position?esc(placeLabel(x.position)):'—')+'</div><div class="rank-name">'+esc(x.name)+'</div><div class="rank-pct">'+esc(x.winRate||'—')+'</div></div>').join('');
const multiCourt=Array.isArray(d.courts)&&d.courts.length>1;
if(multiCourt){
 const courtCards=d.courts.map(court=>{
  const courtNumber=Number(court.court||1);
  const status=court.status==='playing'?'PLAYING':court.status==='waiting'?'WAITING':'COMPLETE';
  const timerNode=(court.timerSeconds||court.timerRunning)?'<strong class="spectator-court-timer game-timer" data-spectator-timer="1" data-running="'+(court.timerRunning?'true':'false')+'" data-started-at="'+esc(court.timerStartedAt??'')+'" data-base="'+esc(court.timerSeconds??0)+'">'+formatElapsed(court.timerSeconds)+'</strong>':'';
  const teams=court.status==='complete'?'<div class="court-card-complete"><b>COURT '+esc(courtNumber)+' COMPLETE</b></div>':('<div class="matchup spectator-court-matchup">'+r.renderMatchup(court.teams||[],{variant:'spectator'})+'</div><p class="hint">Sitting out: '+esc((court.sitting||[]).join(', ')||'None')+'</p>'+(court.status==='waiting'&&court.waitingFor?'<div class="spectator-court-waiting"><b>WAITING FOR PLAYERS</b><span>Waiting for '+esc(court.waitingFor.player)+' (Court '+esc(Number(court.waitingFor.court||1))+')</span></div>':''));
  return '<article class="card spectator-section spectator-court-card" data-spectator-court="'+esc(courtNumber)+'"><div class="live-spectator-heading"><div><span class="eyebrow">COURT '+esc(courtNumber)+'</span><h2>GAME '+esc(court.gameNo??'—')+'</h2></div><div class="spectator-court-meta">'+timerNode+'<span class="badge">'+status+'</span></div></div>'+teams+'</article>';
 }).join('');
 const headerTimer='';
 app.innerHTML='<main class="shared-live-page"><div class="spectator-layout"><section class="card spectator-section spectator-header"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE COURT DISPLAY · '+esc(d.sessionCode||'')+'</span><h1>'+esc(d.season||'Court Rotation')+'</h1><p class="hint"><span class="live-pill">LIVE · updates automatically</span> <span class="spectator-connection-status">'+(connectionOnline?'Realtime connected':'Reconnecting…')+'</span></p><p class="hint spectator-phone-lock-hint">If your phone was locked, reload to refresh.</p></div>'+headerTimer+'</div></section><section class="spectator-court-list">'+courtCards+'</section><section class="card spectator-section spectator-progress-section"><div class="spectator-progress-label"><span>Progress</span><b>'+completed+' / '+total+' games</b></div><div class="spectator-progress"><span style="width:'+progress+'%"></span></div></section><section class="spectator-game-list">'+(games||'<p class="hint">No schedule available.</p>')+'</section><section class="card spectator-section spectator-upnext"><div class="live-spectator-heading"><div><span class="eyebrow">UP NEXT</span><h2>Next games</h2></div></div>'+(up||'<p class="hint">No upcoming games.</p>')+'</section><section class="card spectator-section spectator-match-log"><div class="live-spectator-heading"><div><span class="eyebrow">MATCH LOG</span><h2>Completed games</h2></div></div>'+(log||'<p class="hint">No completed games yet.</p>')+'</section><section class="card spectator-section spectator-leaderboard"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE LEADERBOARD</span><h2>Winners & losers</h2></div><span class="live-pill">LIVE</span></div>'+(ranks||'<p class="hint">No results yet. Complete games and record the standings.</p>')+'</section><p class="hint spectator-updated">Updated '+esc(new Date(d.updatedAt||Date.now()).toLocaleTimeString())+'</p></div></main>';
 startSpectatorCourtTimers(d.courts);
 return;
}
const timer=current.timerRunning?'<div class="spectator-live-timer-wrap"><span class="eyebrow">LIVE TIMER</span><strong id="spectatorLiveTimer">'+formatElapsed(current.timerSeconds)+'</strong></div>':'';
app.innerHTML='<main class="shared-live-page"><div class="spectator-layout"><section class="card spectator-section spectator-header"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE COURT DISPLAY · '+esc(d.sessionCode||'')+'</span><h1>'+esc(d.season||'Court Rotation')+'</h1><p class="hint"><span class="live-pill">LIVE · updates automatically</span> <span class="spectator-connection-status">'+(connectionOnline?'Realtime connected':'Reconnecting…')+'</span></p><p class="hint spectator-phone-lock-hint">If your phone was locked, reload to refresh.</p></div>'+timer+'</div></section><section class="card spectator-section spectator-current"><div class="eyebrow">NOW PLAYING · '+esc(current.court?'COURT '+current.court:'COURT —')+'</div><h2>'+esc(current.game||'Waiting')+'</h2>'+r.renderMatchup(currentTeams,{variant:'spectator'})+'<p class="hint">'+esc(Array.isArray(current.sitting)?'Sitting out: '+(current.sitting.join(', ')||'None'):current.sitting||'')+'</p></section><section class="card spectator-section spectator-progress-section"><div class="spectator-progress-label"><span>Progress</span><b>'+completed+' / '+total+' games</b></div><div class="spectator-progress"><span style="width:'+progress+'%"></span></div></section><section class="spectator-game-list">'+(games||'<p class="hint">No schedule available.</p>')+'</section><section class="card spectator-section spectator-upnext"><div class="live-spectator-heading"><div><span class="eyebrow">UP NEXT</span><h2>Next games</h2></div></div>'+(up||'<p class="hint">No upcoming games.</p>')+'</section><section class="card spectator-section spectator-match-log"><div class="live-spectator-heading"><div><span class="eyebrow">MATCH LOG</span><h2>Completed games</h2></div></div>'+(log||'<p class="hint">No completed games yet.</p>')+'</section><section class="card spectator-section spectator-leaderboard"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE LEADERBOARD</span><h2>Winners & losers</h2></div><span class="live-pill">LIVE</span></div>'+(ranks||'<p class="hint">No results yet. Complete games and record the standings.</p>')+'</section><p class="hint spectator-updated">Updated '+esc(new Date(d.updatedAt||Date.now()).toLocaleTimeString())+'</p></div></main>';
startSpectatorTimer(current);
}
function renderLeaderboard(d){document.body.classList.add('spectator-mode');const app=document.querySelector('.app');if(!app)return;const rows=Array.isArray(d?.rankings)?d.rankings:[],hasResults=rows.some(x=>Number(x.g)>0),ranked=rows.map(x=>'<article class="rank-row '+(Number(x.position)===1?'first-place':'')+'"><div class="rank-identity"><div class="rank-pos">'+(x.position?esc(placeLabel(x.position)):'—')+'</div><div class="rank-name">'+esc(x.name)+'</div></div><div class="rank-stats"><span class="rank-chip">'+Math.max(0,Number(x.w)||0)+'W</span><span class="rank-chip">'+Math.max(0,Number(x.l)||0)+'L</span><span class="rank-chip">'+Math.max(0,Number(x.g)||0)+' '+(Number(x.g)===1?'game':'games')+'</span><span class="rank-chip rank-pct">'+esc(x.winRate||'—')+'</span></div></article>').join('');app.innerHTML='<main class="shared-live-page"><section class="card spectator-section live-leaderboard-page"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE LEADERBOARD · '+esc(d.sessionCode||'')+'</span><h1>'+esc(d.season||'Court Rotation')+'</h1><p class="hint">Read-only standings · updates automatically while the session is in progress. <span class="spectator-connection-status">'+(connectionOnline?'Realtime connected':'Reconnecting…')+'</span></p></div><span class="live-pill">LIVE</span></div>'+(hasResults?'':'<p class="hint live-leaderboard-empty">No results yet. Complete games and record a winner to build the standings.</p>')+'<div class="rankings-list">'+(ranked||'<p class="hint">No players available.</p>')+'</div><p class="hint spectator-updated">Updated '+esc(new Date(d.updatedAt||Date.now()).toLocaleTimeString())+'</p></section></main>'}
function handleSpectatorVisibility(){if(!spectatorCode)return;if(document.visibilityState==='hidden'){pollingPaused=true;clearInterval(pollTimer);pollTimer=0;clearTimeout(retryTimer);retryTimer=0;spectatorRetryWaiting=true;return}pollingPaused=false;clearTimeout(retryTimer);retryTimer=0;if(lastSpectatorPayload){if(spectatorMode==='leaderboard')renderLeaderboard(lastSpectatorPayload);else renderSnapshot(lastSpectatorPayload)}if(!spectatorChannel)connectSpectator(spectatorCode,spectatorMode);startPolling()}document.addEventListener('visibilitychange',handleSpectatorVisibility);window.addEventListener('online',()=>{if(spectatorCode&&!pollingPaused){if(!spectatorChannel)connectSpectator(spectatorCode,spectatorMode);poll()}});
async function spectator(){const p=new URLSearchParams(location.search),mode=p.get('view')==='live-leaderboard'?'leaderboard':p.get('view')==='spectator'?'spectator':'';if(!mode)return;const live=p.get('live')||p.get('live-leaderboard'),encoded=p.get('s');if(encoded&&mode==='spectator'){try{const raw=decodeURIComponent(encoded).replace(/ /g,'+');renderSnapshot(JSON.parse(decodeURIComponent(escape(atob(raw)))));return}catch(e){console.warn('CRG snapshot decode failed:',e)}}if(!live){renderConnecting('This live link is missing its session code.');return}spectatorMode=mode;spectatorCode=live;lastRenderedAt=0;pollingPaused=false;spectatorRetryWaiting=false;renderConnecting();const initial=await fetchState(live);if(initial.kind==='ok')applyPayload(initial.payload,'poll');else if(initial.kind==='ended'){renderSessionEnded();return}else{updateConnection('Live sync unavailable');renderLiveFailure('The shared session could not be reached. Retrying automatically when the connection is available.')}await connectSpectator(live,mode);startPolling()}
spectator();
})();