(()=>{'use strict';
const CONFIG=window.CRG_SUPABASE_CONFIG||{},TABLE='court_rotation_sessions',HOST_KEY='crg-supabase-host-key-v1',POLL_MS=4000;
let hostClient=null,spectatorClient=null,hostChannel=null,spectatorChannel=null,hostCode='',spectatorCode='',publishTimer=0,pollTimer=0,retryTimer=0,retryAttempt=0,connectionOnline=false,lastRenderedAt=0;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const waitConfig=async()=>{try{await window.CRG_SUPABASE_CONFIG_READY}catch{}return CONFIG};
const hostKeyFor=code=>{const key=HOST_KEY+':'+code;try{let v=localStorage.getItem(key);if(v)return v;const b=new Uint8Array(32);crypto.getRandomValues(b);v=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');localStorage.setItem(key,v);return v}catch{return'crg-'+code+'-'+Math.random().toString(36).slice(2)+Date.now().toString(36)}};
async function client(forHost=false,code=''){await waitConfig();if(!CONFIG.url||!CONFIG.publishableKey)return null;if(forHost&&hostClient)return hostClient;if(!forHost&&spectatorClient)return spectatorClient;try{if(!window.supabase?.createClient){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}if(!window.supabase?.createClient)return null;const opts=forHost&&code?{global:{headers:{'x-crg-host-key':hostKeyFor(code)}}}:{};const c=window.supabase.createClient(CONFIG.url,CONFIG.publishableKey,opts);if(forHost)hostClient=c;else spectatorClient=c;return c}catch(e){console.warn('CRG Supabase client failed:',e);return null}}
function sessionCode(){return($('sessionCodeText')?.textContent||'').match(/CRG-[A-Z0-9]+/)?.[0]||''}
function snapshot(){return typeof window.CRG_GET_LIVE_SNAPSHOT==='function'?window.CRG_GET_LIVE_SNAPSHOT():null}
async function persist(data,code){const sb=await client(true,code);if(!sb)return false;if(typeof sb.from!=='function')return true;try{const{error}=await sb.from(TABLE).upsert({session_code:code,host_key:hostKeyFor(code),payload:data,updated_at:data.updatedAt||new Date().toISOString()},{onConflict:'session_code'});if(error){console.warn('CRG live state write failed:',error);return false}return true}catch(e){console.warn('CRG live state write failed:',e);return false}}
async function fetchState(code){const sb=await client(false);if(!sb||typeof sb.from!=='function')return null;try{const{data,error}=await sb.from(TABLE).select('payload,updated_at').eq('session_code',code).maybeSingle();if(error){console.warn('CRG live state read failed:',error);return null}return data?.payload?{...data.payload,updatedAt:data.payload.updatedAt||data.updated_at||new Date().toISOString()}:null}catch(e){console.warn('CRG live state read failed:',e);return null}}
async function channel(topic,events,onStatus){const sb=await client(false);if(!sb?.channel)return null;return await new Promise(resolve=>{let done=false,settle=v=>{if(!done){done=true;resolve(v)}};const ch=sb.channel(topic,{config:{broadcast:{self:false}}});Object.entries(events).forEach(([name,fn])=>ch.on('broadcast',{event:name},fn));try{ch.subscribe(status=>{onStatus?.(status);if(status==='SUBSCRIBED')settle(ch);else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED')settle(null)})}catch(e){console.warn('CRG realtime subscribe failed:',e);settle(null)}setTimeout(()=>settle(null),7000)})}
async function ensureHostChannel(code){if(hostChannel&&hostCode===code)return true;if(hostChannel){try{await hostChannel.unsubscribe()}catch{}hostChannel=null}const ch=await channel('crg-session-'+code,{'request-state':()=>publish(true)},status=>{if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status))hostChannel=null});if(!ch)return false;hostChannel=ch;hostCode=code;return true}
async function publish(force=false){const data=snapshot(),code=data?.sessionCode||sessionCode();if(!data||!code)return{storageReady:false,realtimeReady:false};const storageReady=await persist(data,code),realtimeReady=await ensureHostChannel(code);if(realtimeReady){try{await hostChannel.send({type:'broadcast',event:'state',payload:{...data,updatedAt:new Date().toISOString()}})}catch(e){console.warn('CRG realtime broadcast failed:',e)}}return{storageReady,realtimeReady}}
function queuePublish(){clearTimeout(publishTimer);publishTimer=setTimeout(()=>{if(!document.body.classList.contains('spectator-mode'))publish(false)},120)}
async function copyUrl(url,promptText){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(url);return true}}catch(e){console.warn('CRG copy failed:',e)}try{prompt(promptText,url);return true}catch{return false}}
function setLiveButton(mode){const b=$('copyLiveSpectatorBtn');if(b)b.textContent=mode==='snapshot'?'Copy read-only snapshot link':'Copy live spectator link'}
function encodeSnapshot(d){const bytes=new TextEncoder().encode(JSON.stringify(d));let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return encodeURIComponent(btoa(bin))}
async function copySnapshot(){const d=snapshot(),code=d?.sessionCode||sessionCode();if(!code){toast('Generate a rotation first.');return false}const url=location.origin+location.pathname+'?s='+encodeSnapshot(d)+'&view=spectator';const ok=await copyUrl(url,'Copy this read-only spectator link:');if(ok)toast('Read-only snapshot link copied');return ok}
async function startHost(){const code=sessionCode()||snapshot()?.sessionCode;if(!code){toast('Generate a rotation first.');return}const r=await publish(true);if(r.storageReady){setLiveButton('live');const url=location.origin+location.pathname+'?live='+encodeURIComponent(code)+'&view=spectator';const ok=await copyUrl(url,'Copy this live spectator link:');if(ok)toast(r.realtimeReady?'Live spectator link copied':'Live spectator link copied · realtime reconnecting');return}setLiveButton('snapshot');await copySnapshot();toast('Live storage unavailable · use the snapshot link instead')}
function toast(msg){let t=$('crgToast');if(!t){t=document.createElement('div');t.id='crgToast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2600)}
window.CRG_PUBLISH_LIVE=()=>publish(true);window.CRG_LIVE_SYNC_TOUCH=queuePublish;window.CRG_START_LIVE_SYNC=()=>publish(true);window.CRG_COPY_LIVE_SPECTATOR_LINK=startHost;window.CRG_COPY_LIVE_LINK=startHost;
let spectatorMode='',spectatorCode='',pollBusy=false;
function updateConnection(message){connectionOnline=message==='Realtime connected';document.body.dataset.spectatorConnection=connectionOnline?'online':'offline';document.querySelectorAll('.spectator-connection-status').forEach(n=>n.textContent=message)}
function renderConnecting(message='Connecting to the shared session…'){document.body.classList.add('spectator-mode');const app=document.querySelector('.app');if(!app)return;app.innerHTML='<main class="shared-live-page"><section class="card spectator-section spectator-connect-card"><span class="eyebrow">LIVE COURT DISPLAY</span><h1>Reconnecting…</h1><p class="hint">'+esc(message)+'</p><button type="button" class="btn secondary" id="spectatorRetryBtn">Retry now</button><p class="hint spectator-fallback-label"><b>Read-only snapshot fallback:</b> ask the host for the frozen snapshot link.</p></section></main>';$('spectatorRetryBtn')?.addEventListener('click',()=>{retryAttempt=0;connectSpectator(spectatorCode,spectatorMode)})}
function applyPayload(d,source){if(!d)return false;const t=Date.parse(d?.updatedAt||'');if(t&&t<lastRenderedAt)return false;if(t)lastRenderedAt=t;if(spectatorMode==='leaderboard')renderLeaderboard(d);else renderSnapshot(d);if(source==='realtime')updateConnection('Realtime connected');return true}
async function poll(){if(!spectatorCode||pollBusy)return;pollBusy=true;const d=await fetchState(spectatorCode);pollBusy=false;if(d){applyPayload(d,'poll');return}updateConnection('Reconnecting…');if(!document.querySelector('.spectator-current,.live-leaderboard-page'))renderConnecting('The shared session is not available yet. Retrying automatically.')}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(poll,POLL_MS);poll()}
function retryConnect(){clearTimeout(retryTimer);const delay=Math.min(10000,1200*2**Math.min(retryAttempt++,3));retryTimer=setTimeout(()=>connectSpectator(spectatorCode,spectatorMode),delay)}
async function connectSpectator(code,mode){if(spectatorChannel){try{await spectatorChannel.unsubscribe()}catch{}spectatorChannel=null}const ch=await channel('crg-session-'+code,{'state':p=>{if(p?.payload)applyPayload(p.payload,'realtime')}},status=>{if(status==='SUBSCRIBED'){retryAttempt=0;updateConnection('Realtime connected')}else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status)){spectatorChannel=null;updateConnection('Reconnecting…');retryConnect()}});if(!ch){updateConnection('Reconnecting…');retryConnect();return}spectatorChannel=ch}
function stopSpecTimer(){if(window.CRG_SPECTATOR_TIMER)clearInterval(window.CRG_SPECTATOR_TIMER)}
function startSpectatorTimer(cur){stopSpecTimer();const node=$('spectatorLiveTimer');if(!node||!cur?.timerRunning)return;const start=Number(cur.timerStartedAt),base=Number(cur.timerSeconds)||0;const tick=()=>node.textContent=formatElapsed(Number.isFinite(start)?Math.max(0,Math.floor((Date.now()-start)/1000)):base);tick();window.CRG_SPECTATOR_TIMER=setInterval(tick,1000)}
function formatElapsed(sec){const n=Math.max(0,Math.floor(Number(sec)||0));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function placeLabel(n){const j=n%10,k=n%100;return n===1?'🏆🥇 1st':n===2?'🥈 2nd':n===3?'🥉 3rd':n+(j===1&&k!==11?'st':j===2&&k!==12?'nd':j===3&&k!==13?'rd':'th')}
function resultSummaryMarkup(r){if(!r)return'';const parts=['🏆 Winner: '+(r.winnerNames||[]).join(' and ')];if(Number.isFinite(Number(r.durationSeconds)))parts.push('Won in '+formatElapsed(r.durationSeconds));if(r.score&&Number.isFinite(Number(r.score.a))&&Number.isFinite(Number(r.score.b)))parts.push((r.winner===0?r.score.a:r.score.b)+' – '+(r.winner===0?r.score.b:r.score.a));return'<p class="spectator-result-summary">'+esc(parts.join(' · '))+'</p>'}
function renderSnapshot(d){document.body.classList.add('spectator-mode');const app=document.querySelector('.app');if(!app)return;const current=d.current||{},p=d.progress||{},teams=current.teams?.flat()?.length?current.teams:(d.schedule?.[Number(current.index)]?.teams||[]),completed=Number(p.completed)||0,total=Number(p.total)||Number(d.schedule?.length)||0,progress=Number.isFinite(Number(p.percent))?Math.max(0,Math.min(100,Number(p.percent))):total?Math.round(completed/total*100):0,r=window.CRG_TEAM_RENDERER,match=g=>r.renderMatchup(g.teams,{variant:'spectator'}),games=(d.schedule||[]).map(g=>'<article class="card spectator-section spectator-game"><div class="eyebrow">GAME '+esc(g.index)+' · COURT '+esc(g.court||1)+'</div>'+match(g)+(g.done&&g.result?resultSummaryMarkup(g.result):'<p class="hint">Upcoming</p>')+'</article>').join(''),up=(d.upNext||[]).map(g=>'<article class="spectator-upnext-row"><b>GAME '+esc(g.index||'')+'</b>'+r.renderMatchup(g.teams,{variant:'spectator',className:'spectator-upnext-matchup'})+'</article>').join(''),log=(d.matchLog||[]).map(g=>'<article class="spectator-log-row"><div class="spectator-log-head"><b>GAME '+esc(g.index||'')+'</b><span>COURT '+esc(g.court||1)+'</span></div>'+r.renderMatchup(g.teams,{variant:'spectator',className:'spectator-log-matchup'})+(g.result?resultSummaryMarkup(g.result):'')+'</article>').join(''),timer=current.timerRunning?'<div class="spectator-live-timer-wrap"><span class="eyebrow">LIVE TIMER</span><strong id="spectatorLiveTimer">'+formatElapsed(current.timerSeconds)+'</strong></div>':'',ranks=(d.rankings||[]).map(x=>'<div class="rank-row"><div class="rank-pos">'+(x.position?esc(placeLabel(x.position)):'—')+'</div><div class="rank-name">'+esc(x.name)+'</div><div class="rank-pct">'+esc(x.winRate||'—')+'</div></div>').join('');
app.innerHTML='<main class="shared-live-page"><div class="spectator-layout"><section class="card spectator-section spectator-header"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE COURT DISPLAY · '+esc(d.sessionCode||'')+'</span><h1>'+esc(d.season||'Court Rotation')+'</h1><p class="hint"><span class="live-pill">LIVE · updates automatically</span> <span class="spectator-connection-status">'+(connectionOnline?'Realtime connected':'Reconnecting…')+'</span></p></div>'+timer+'</div></section><section class="card spectator-section spectator-current"><div class="eyebrow">NOW PLAYING · '+esc(current.court?'COURT '+current.court:'COURT —')+'</div><h2>'+esc(current.game||'Waiting')+'</h2>'+r.renderMatchup(teams,{variant:'spectator'})+'<p class="hint">'+esc(Array.isArray(current.sitting)?'Sitting out: '+(current.sitting.join(', ')||'None'):current.sitting||'')+'</p></section><section class="card spectator-section spectator-progress-section"><div class="spectator-progress-label"><span>Progress</span><b>'+completed+' / '+total+' games</b></div><div class="spectator-progress"><span style="width:'+progress+'%"></span></div></section><section class="spectator-game-list">'+(games||'<p class="hint">No schedule available.</p>')+'</section><section class="card spectator-section spectator-upnext"><div class="live-spectator-heading"><div><span class="eyebrow">UP NEXT</span><h2>Next games</h2></div></div>'+(up||'<p class="hint">No upcoming games.</p>')+'</section><section class="card spectator-section spectator-match-log"><div class="live-spectator-heading"><div><span class="eyebrow">MATCH LOG</span><h2>Completed games</h2></div></div>'+(log||'<p class="hint">No completed games yet.</p>')+'</section><section class="card spectator-section spectator-leaderboard"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE LEADERBOARD</span><h2>Winners & losers</h2></div><span class="live-pill">LIVE</span></div>'+(ranks||'<p class="hint">No results yet. Complete games and record the standings.</p>')+'</section><p class="hint spectator-updated">Updated '+esc(new Date(d.updatedAt||Date.now()).toLocaleTimeString())+'</p></div></main>';startSpectatorTimer(current)}
function renderLeaderboard(d){document.body.classList.add('spectator-mode');const app=document.querySelector('.app');if(!app)return;const rows=Array.isArray(d?.rankings)?d.rankings:[],hasResults=rows.some(x=>Number(x.g)>0),ranked=rows.map(x=>'<article class="rank-row '+(Number(x.position)===1?'first-place':'')+'"><div class="rank-identity"><div class="rank-pos">'+(x.position?esc(placeLabel(x.position)):'—')+'</div><div class="rank-name">'+esc(x.name)+'</div></div><div class="rank-stats"><span class="rank-chip">'+Math.max(0,Number(x.w)||0)+'W</span><span class="rank-chip">'+Math.max(0,Number(x.l)||0)+'L</span><span class="rank-chip">'+Math.max(0,Number(x.g)||0)+' '+(Number(x.g)===1?'game':'games')+'</span><span class="rank-chip rank-pct">'+esc(x.winRate||'—')+'</span></div></article>').join('');app.innerHTML='<main class="shared-live-page"><section class="card spectator-section live-leaderboard-page"><div class="live-spectator-heading"><div><span class="eyebrow">LIVE LEADERBOARD · '+esc(d.sessionCode||'')+'</span><h1>'+esc(d.season||'Court Rotation')+'</h1><p class="hint">Read-only standings · updates automatically while the session is in progress. <span class="spectator-connection-status">'+(connectionOnline?'Realtime connected':'Reconnecting…')+'</span></p></div><span class="live-pill">LIVE</span></div>'+(hasResults?'':'<p class="hint live-leaderboard-empty">No results yet. Complete games and record a winner to build the standings.</p>')+'<div class="rankings-list">'+(ranked||'<p class="hint">No players available.</p>')+'</div><p class="hint spectator-updated">Updated '+esc(new Date(d.updatedAt||Date.now()).toLocaleTimeString())+'</p></section></main>'}
async function spectator(){const p=new URLSearchParams(location.search),mode=p.get('view')==='live-leaderboard'?'leaderboard':p.get('view')==='spectator'?'spectator':'';if(!mode)return;const live=p.get('live')||p.get('live-leaderboard'),encoded=p.get('s');if(encoded&&mode==='spectator'){try{const raw=decodeURIComponent(encoded).replace(/ /g,'+');renderSnapshot(JSON.parse(decodeURIComponent(escape(atob(raw))));return}catch(e){console.warn('CRG snapshot decode failed:',e)}}if(!live){renderConnecting('This live link is missing its session code.');return}spectatorMode=mode;spectatorCode=live;lastRenderedAt=0;renderConnecting();const initial=await fetchState(live);if(initial)applyPayload(initial,'poll');else updateConnection('Reconnecting…');await connectSpectator(live,mode);startPolling()}
spectator();
})();