(()=>{'use strict';const teams=document.getElementById('currentTeams'),names=document.getElementById('names');
if(!teams||!names)return;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const clean=v=>String(v||'').trim();
function roster(){return names.value.split(/\r?\n/).map(clean).filter(Boolean)}
function storedSkills(){try{return JSON.parse(localStorage.getItem('crg-skills-v1')||'{}')||{}}catch{return{}}}
function skillByName(){const list=roster(),src=window.CRG_PLAYER_SKILLS||{},stored=storedSkills(),out=new Map();list.forEach((name,i)=>out.set(name.toLocaleLowerCase(),String(src[i+1]||stored[name]||'Intermediate').toLocaleLowerCase()));return out}
function formatPlayer(name,skill='Intermediate'){return `<span class="live-player"><span class="live-player-name">${esc(name)}</span><small class="live-player-skill"> · ${esc(skill)}</small></span>`}
window.CRG_FORMAT_LIVE_PLAYER=formatPlayer;
function formatTeam(playerNames,map){return `<div class="live-team-block">${playerNames.map(n=>formatPlayer(n,map.get(clean(n).toLocaleLowerCase())||'intermediate')).join('<span class="live-plus" aria-hidden="true">+</span>')}</div>`}
function render(){const raw=teams.textContent.replace(/\s+/g,' ').trim();if(!raw||raw==='—')return;const parts=raw.split(/\s+VS\s+/i);if(parts.length!==2)return;const teamA=parts[0].split(/\s*\+\s*/).map(clean).filter(Boolean),teamB=parts[1].split(/\s*\+\s*/).map(clean).filter(Boolean);if(teamA.length<2||teamB.length<2)return;const map=skillByName();const html=`<div class="team">${formatTeam(teamA,map)}</div><div class="versus">VS</div><div class="team">${formatTeam(teamB,map)}</div>`;if(teams.innerHTML!==html)teams.innerHTML=html}
const style=document.createElement('style');style.textContent='.live-team-block{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;min-width:0;max-width:100%}.live-player{display:flex;flex-direction:column;align-items:center;justify-content:center;min-width:0;max-width:100%;line-height:1.05;white-space:nowrap}.live-player-name{display:block;max-width:100%;overflow-wrap:normal;word-break:normal}.live-player-skill{display:block;margin-top:4px;font-size:.42em;line-height:1;font-weight:800;letter-spacing:.04em;text-transform:uppercase;color:var(--muted);white-space:nowrap}.live-plus{display:flex;align-items:center;justify-content:center;color:var(--muted);font-weight:900;line-height:1;min-height:12px}.matchup .team{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:7px!important;min-width:0}';document.head.appendChild(style);
// Safe render hook: no MutationObserver watches #currentTeams. App rendering explicitly calls this once after replacing the current matchup, so there is no self-triggering DOM feedback loop.
window.CRG_RENDER_LIVE_DISPLAY=render;render();})();