(()=>{'use strict';
const names=document.getElementById('names'),count=document.getElementById('playerCount'),setup=document.getElementById('setupView'),sheet=document.getElementById('sheet'),sheetContent=document.getElementById('sheetContent');
if(!names||!setup)return;
const SKILL_KEY='crg-skills-v1',DRAFT_KEY='crg-session-v4';
const read=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??d}catch{return d}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const title=v=>String(v||'').trim().replace(/\s+/g,' ').replace(/(^|[\s'-])([a-zà-ÿ])/g,(_,p,c)=>p+c.toLocaleUpperCase());
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let skills=read(SKILL_KEY,{}),draft=read(DRAFT_KEY,null),roster=[];
const initial=(draft?.names||[]).filter(Boolean);if(initial.length)roster=initial.map(title);else if(names.value.trim())roster=names.value.split(/\r?\n/).map(title).filter(Boolean);
function exposeSkills(){window.CRG_PLAYER_SKILLS=Object.fromEntries(roster.map((n,i)=>[i+1,skills[n]||'Intermediate']))}
function sync(){names.value=roster.join('\n');names.dispatchEvent(new Event('input',{bubbles:true}));exposeSkills();if(count)count.textContent=roster.length;render()}
function close(){if(!sheet)return;sheet.hidden=true;sheet.classList.remove('modal-open');document.body.classList.remove('modal-open')}
function commitNames(values){let added=0;const seen=new Set(roster.map(n=>n.toLocaleLowerCase()));values.map(title).filter(Boolean).forEach(v=>{const key=v.toLocaleLowerCase();if(seen.has(key))return;seen.add(key);roster.push(v);if(!skills[v])skills[v]='Intermediate';added++});write(SKILL_KEY,skills);sync();return added}
function openAdd(){if(!sheet||!sheetContent)return;sheetContent.innerHTML='<div class="sheet-title">Add players</div><p class="hint">Add one or multiple players. Enter one name per line.</p><label class="sr-only" for="newPlayerNames">Player names</label><textarea id="newPlayerNames" class="modal-input modal-textarea" rows="7" autocomplete="off" placeholder="Player 1\nPlayer 2\nPlayer 3"></textarea><div class="confirm-actions player-modal-actions"><button type="button" class="btn modal-cancel" id="playerCancel">Cancel</button><button type="button" class="btn modal-confirm" id="playerAddConfirm">Add players</button></div>';sheet.hidden=false;sheet.classList.add('modal-open');document.body.classList.add('modal-open');const input=document.getElementById('newPlayerNames');input?.focus();document.getElementById('playerCancel')?.addEventListener('click',close,{once:true});document.getElementById('playerAddConfirm')?.addEventListener('click',()=>{const values=String(input?.value||'').split(/\r?\n/);const added=commitNames(values);if(!added){input?.focus();input?.classList.add('is-invalid');return}close()},{once:true});input?.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
function removePlayer(i){const n=roster[i];if(!n)return;roster.splice(i,1);delete skills[n];write(SKILL_KEY,skills);sync()}
function clearAll(){roster=[];skills={};localStorage.removeItem(SKILL_KEY);localStorage.removeItem(DRAFT_KEY);names.value='';names.dispatchEvent(new Event('input',{bubbles:true}));exposeSkills();if(count)count.textContent='0';render()}
function changeSkill(n,v){skills[n]=v;write(SKILL_KEY,skills);sync()}
function render(){const card=setup.querySelector('.player-card-ui'),rows=card?.querySelector('#playerList');if(!rows)return;rows.innerHTML=roster.length?`<div class="player-list-head"><span>Names</span><span>Skill levels</span><span aria-hidden="true"></span></div>`+roster.map((n,i)=>`<div class="player-row"><span class="player-name">${esc(n)}</span><select data-skill-player="${esc(n)}" aria-label="Skill level for ${esc(n)}"><option${(skills[n]||'Intermediate')==='Beginner'?' selected':''}>Beginner</option><option${(skills[n]||'Intermediate')==='Intermediate'?' selected':''}>Intermediate</option><option${(skills[n]||'Intermediate')==='Advanced'?' selected':''}>Advanced</option></select><button type="button" class="icon-btn player-remove" data-remove-player="${i}" aria-label="Remove ${esc(n)}" title="Remove player">×</button></div>`).join(''):'<div class="empty">No players yet. Add players to begin.</div>';rows.querySelectorAll('[data-skill-player]').forEach(s=>s.addEventListener('change',()=>changeSkill(s.dataset.skillPlayer,s.value)));rows.querySelectorAll('[data-remove-player]').forEach(b=>b.addEventListener('click',()=>removePlayer(Number(b.dataset.removePlayer))));const counter=card.querySelector('[data-player-total]');if(counter)counter.textContent=`${roster.length} players`;exposeSkills()}
function watchReset(){if(!sheet||!sheetContent)return;new MutationObserver(()=>{const titleText=sheetContent.querySelector('.sheet-title')?.textContent?.trim().toLowerCase();const confirm=document.getElementById('modalConfirm');if(titleText==='reset everything'&&confirm&&!confirm.dataset.playerResetHooked){confirm.dataset.playerResetHooked='1';confirm.addEventListener('click',()=>setTimeout(clearAll,0),{once:true})}}).observe(sheetContent,{childList:true,subtree:true})}
function install(){const grid=setup.querySelector('.grid-setup'),oldPlayer=grid?.children?.[0],generate=grid?.children?.[1];if(!grid||!oldPlayer||!generate||oldPlayer.dataset.uiMerged)return;oldPlayer.dataset.uiMerged='1';const preservedNames=names,preservedCount=count;while(oldPlayer.firstChild)oldPlayer.removeChild(oldPlayer.firstChild);const head=document.createElement('div');head.className='card-head';head.innerHTML='<h3>Players</h3>';if(preservedCount){preservedCount.className='count';head.appendChild(preservedCount)}const action=document.createElement('div');action.className='player-ui-actions';const add=document.createElement('button');add.id='addPlayerBtn';add.type='button';add.className='btn secondary';add.textContent='+ Add players';action.appendChild(add);const clear=document.createElement('button');clear.id='clearAllPlayersBtn';clear.type='button';clear.className='btn ghost';clear.textContent='Clear all';action.appendChild(clear);preservedNames.hidden=true;preservedNames.setAttribute('aria-hidden','true');preservedNames.style.display='none';const ui=document.createElement('div');ui.className='player-card-ui';ui.innerHTML='<div class="player-ui-col"><div class="player-ui-col-head"><b>Player roster</b><span class="hint" data-player-total>0 players</span></div><div id="playerList" class="player-list"></div></div>';oldPlayer.append(head,preservedNames,action,ui);grid.insertAdjacentElement('afterend',generate);generate.classList.add('generate-card');add.addEventListener('click',openAdd);clear.addEventListener('click',()=>{if(!roster.length)return;clearAll()});setup.querySelector('#skillSetup')?.remove();setup.querySelector('#pasteBtn')?.remove();setup.querySelector('#clearNamesBtn')?.remove();sync()}
const observer=new MutationObserver(()=>{if(!setup.querySelector('.player-card-ui'))install()});observer.observe(setup,{childList:true,subtree:true});watchReset();install();
})();
