(()=>{'use strict';
const names=document.getElementById('names'),count=document.getElementById('playerCount'),setup=document.getElementById('setupView'),sheet=document.getElementById('sheet'),sheetContent=document.getElementById('sheetContent');
if(!names||!setup)return;
const SKILL_KEY='crg-skills-v1',DRAFT_KEY='crg-session-v4',SKILL_OPTIONS=['Beginner','Advanced Beginner','Intermediate','Advanced Intermediate','Advanced','Expert'];
const read=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??d}catch{return d}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const title=v=>String(v||'').trim().replace(/\s+/g,' ').replace(/(^|[\s'-])([a-zà-ÿ])/g,(_,p,c)=>p+c.toLocaleUpperCase());
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let skills=read(SKILL_KEY,{}),draft=read(DRAFT_KEY,null),roster=[];
const initial=(draft?.names||[]).filter(Boolean);if(initial.length)roster=initial.map(title);else if(names.value.trim())roster=names.value.split(/\r?\n/).map(title).filter(Boolean);
function normalizeSkill(v){return SKILL_OPTIONS.includes(v)?v:'Beginner'}
function exposeSkills(){window.CRG_PLAYER_SKILLS=Object.fromEntries(roster.map((n,i)=>[i+1,normalizeSkill(skills[n])]))}
function sync(){names.value=roster.join('\n');names.dispatchEvent(new Event('input',{bubbles:true}));if(count)count.textContent=roster.length;exposeSkills();render()}
function close(){if(!sheet)return;sheet.hidden=true;sheet.classList.remove('modal-open');document.body.classList.remove('modal-open');const x=document.getElementById('sheetClose');if(x)x.hidden=false}
function commitNames(values){let added=0;const seen=new Set(roster.map(n=>n.toLocaleLowerCase()));values.map(title).filter(Boolean).forEach(v=>{const key=v.toLocaleLowerCase();if(seen.has(key))return;seen.add(key);roster.push(v);skills[v]=normalizeSkill(skills[v]);added++});write(SKILL_KEY,skills);sync();return added}
function showModal(titleText,body,fieldId,fieldTag,placeholder,actionText,commit,options={}){if(!sheet||!sheetContent)return;sheetContent.innerHTML=`<div class="sheet-title">${esc(titleText)}</div><p class="hint">${body}</p><label class="sr-only" for="${fieldId}">Player name</label><${fieldTag} id="${fieldId}" class="modal-input${fieldTag==='textarea'?' modal-textarea':''}" ${fieldTag==='textarea'?'rows="7"':''} autocomplete="off" placeholder="${esc(placeholder)}"></${fieldTag}><div class="confirm-actions player-modal-actions"><button type="button" class="btn modal-cancel" id="playerCancel">Cancel</button><button type="button" class="btn modal-confirm" id="playerConfirm">${esc(actionText)}</button></div>`;sheet.hidden=false;sheet.classList.add('modal-open');document.body.classList.add('modal-open');const x=document.getElementById('sheetClose');if(x)x.hidden=!!options.hideClose;const input=document.getElementById(fieldId),confirm=document.getElementById('playerConfirm');input?.focus();const submit=()=>{const added=commit(String(input?.value||''));if(!added){input?.focus();input?.classList.add('is-invalid');return}close()};confirm?.addEventListener('click',submit,{once:true});document.getElementById('playerCancel')?.addEventListener('click',close,{once:true});input?.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(fieldTag==='input'&&e.key==='Enter'){e.preventDefault();submit()}})}
function openAdd(){showModal('Add player','Enter one player name.','newPlayerName','input','Player name','Add',value=>commitNames([value]))}
function openPaste(){showModal('Paste names','Paste multiple player names, one per line.','pastePlayerNames','textarea','Player 1\nPlayer 2\nPlayer 3','Add names',value=>commitNames(value.split(/\r?\n/)),{hideClose:true})}
function removePlayer(i){const n=roster[i];if(!n)return;roster.splice(i,1);delete skills[n];write(SKILL_KEY,skills);sync()}
function clearAll(){roster=[];skills={};localStorage.removeItem(SKILL_KEY);localStorage.removeItem(DRAFT_KEY);names.value='';names.dispatchEvent(new Event('input',{bubbles:true}));if(count)count.textContent='0';exposeSkills();render()}
function changeSkill(n,v){skills[n]=normalizeSkill(v);write(SKILL_KEY,skills);exposeSkills();render()}
function render(){const card=setup.querySelector('.player-card-ui'),rows=card?.querySelector('#playerList');if(!rows)return;rows.innerHTML=roster.length?`<div class="player-list-head"><span>Names</span><span>Skill levels</span><span aria-hidden="true"></span></div>`+roster.map((n,i)=>{const selected=normalizeSkill(skills[n]);return `<div class="player-row"><span class="player-name">${esc(n)}</span><select data-skill-player="${esc(n)}" aria-label="Skill level for ${esc(n)}">${SKILL_OPTIONS.map(level=>`<option${selected===level?' selected':''}>${esc(level)}</option>`).join('')}</select><button type="button" class="icon-btn player-remove" data-remove-player="${i}" aria-label="Remove ${esc(n)}" title="Remove player">×</button></div>`}).join(''):'<div class="empty">No players yet. Add players to begin.</div>';rows.querySelectorAll('[data-skill-player]').forEach(s=>s.addEventListener('change',()=>changeSkill(s.dataset.skillPlayer,s.value)));rows.querySelectorAll('[data-remove-player]').forEach(b=>b.addEventListener('click',()=>removePlayer(Number(b.dataset.removePlayer))));const counter=card.querySelector('[data-player-total]');if(counter)counter.textContent=`${roster.length} players`}
function watchReset(){if(!sheet||!sheetContent)return;
// Safe observer: it only installs a one-time reset handler guarded by data-player-reset-hooked and does not write the observed subtree itself.
new MutationObserver(()=>{const titleText=sheetContent.querySelector('.sheet-title')?.textContent?.trim().toLowerCase();const confirm=document.getElementById('modalConfirm');if(titleText==='reset everything'&&confirm&&!confirm.dataset.playerResetHooked){confirm.dataset.playerResetHooked='1';confirm.addEventListener('click',()=>setTimeout(clearAll,0),{once:true})}}).observe(sheetContent,{childList:true,subtree:true})}
function install(){const grid=setup.querySelector('.grid-setup'),oldPlayer=grid?.children?.[0],generate=grid?.children?.[1];if(!grid||!oldPlayer||!generate||oldPlayer.dataset.uiMerged)return;oldPlayer.dataset.uiMerged='1';const preservedNames=names,preservedCount=count;document.getElementById('addPlayerBtn')?.remove();document.getElementById('pasteBtn')?.remove();document.getElementById('clearNamesBtn')?.remove();while(oldPlayer.firstChild)oldPlayer.removeChild(oldPlayer.firstChild);const head=document.createElement('div');head.className='card-head';head.innerHTML='<h3>Players</h3>';if(preservedCount){preservedCount.className='count';head.appendChild(preservedCount)}const action=document.createElement('div');action.className='player-ui-actions';const add=document.createElement('button');add.id='playerAddBtn';add.type='button';add.className='btn secondary';add.textContent='+ Add player';const paste=document.createElement('button');paste.id='playerPasteBtn';paste.type='button';paste.className='btn secondary';paste.textContent='Paste names';const clear=document.createElement('button');clear.id='clearAllPlayersBtn';clear.type='button';clear.className='btn ghost';clear.textContent='Clear';action.append(add,paste,clear);preservedNames.hidden=true;preservedNames.setAttribute('aria-hidden','true');preservedNames.style.display='none';const ui=document.createElement('div');ui.className='player-card-ui';ui.innerHTML='<div class="player-ui-col"><div class="player-ui-col-head"><b>Player roster</b><span class="hint" data-player-total>0 players</span></div><div id="playerList" class="player-list"></div></div>';oldPlayer.append(head,preservedNames,action,ui);grid.insertAdjacentElement('afterend',generate);generate.classList.add('generate-card');add.addEventListener('click',openAdd);paste.addEventListener('click',openPaste);clear.addEventListener('click',()=>{if(!roster.length)return;clearAll()});setup.querySelector('#skillSetup')?.remove();sync()}
// Safe observer: setup mutations trigger install only until .player-card-ui exists; install() is guarded by data-ui-merged.
const observer=new MutationObserver(()=>{if(!setup.querySelector('.player-card-ui'))install()});observer.observe(setup,{childList:true,subtree:true});watchReset();install();
})();