(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function sheet(){const sh=$('sheet'),content=$('sheetContent');if(!sh||!content)return null;return{sh,content};}
function close(){const s=sheet();if(!s)return;s.sh.hidden=true;s.sh.classList.remove('modal-open','final-rankings');document.body.classList.remove('modal-open');}
function open(title,html,primary,fn){const s=sheet();if(!s)return; s.content.innerHTML=`<div class="sheet-title">${esc(title)}</div>${html}<div class="confirm-actions facility-actions"><button type="button" class="btn secondary" id="crgPopupCancel">Cancel</button><button type="button" class="btn full" id="crgPopupConfirm">${esc(primary)}</button></div>`;s.sh.hidden=false;s.sh.classList.add('modal-open');document.body.classList.add('modal-open');$('crgPopupCancel')?.addEventListener('click',close,{once:true});$('crgPopupConfirm')?.addEventListener('click',()=>{fn(s.content);},{once:true});}
function field(id,label,value=''){return`<label class="crg-popup-field">${esc(label)}<input id="${id}" type="text" value="${esc(value)}" autocomplete="off"></label>`}
function focus(id){setTimeout(()=>{$(id)?.focus();$(id)?.select?.()},0)}
function savedSession(){try{return JSON.parse(localStorage.getItem('crg-facility-v1:session')||'null')}catch{return null}}
function nameSession(){const s=savedSession();if(!s)return toast('Generate a rotation first');open('Name session',field('crgPopupValue','Session name',s.name||'Live Session'),'Save',host=>{const v=($('crgPopupValue')?.value||'').trim();if(!v){$('crgPopupValue')?.focus();return}close();s.name=v;try{localStorage.setItem('crg-facility-v1:session',JSON.stringify(s));localStorage.setItem('crg-facility-v1:name',v)}catch{};document.getElementById('crgFacilityTools')?.querySelector('.hint')?.classList.remove('is-empty');$('crgFacilityTools')&&document.getElementById('fuName')&&setTimeout(()=>document.getElementById('fuName').focus(),0);window.dispatchEvent(new Event('crg:session-named'));toast('Session named: '+v)});focus('crgPopupValue')}
function checkin(){const ns=(($('names')?.value)||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!ns.length)return toast('Add players first');open('Check-in player',`${field('crgPopupValue','Player name','')}<p class="hint">Enter one of the current player names.</p><div class="crg-popup-options">${ns.map(n=>`<button type="button" class="btn secondary crg-name-option" data-name="${esc(n)}">${esc(n)}</button>`).join('')}</div>`,'Save',host=>{const v=($('crgPopupValue')?.value||'').trim();const who=ns.find(n=>n.toLowerCase()===v.toLowerCase())||v;if(!ns.some(n=>n.toLowerCase()===who.toLowerCase())){toast('Player not found');return}let c={};try{c=JSON.parse(localStorage.getItem('crg-facility-v1:checkins')||'{}')}catch{};c[who]=!c[who];localStorage.setItem('crg-facility-v1:checkins',JSON.stringify(c));close();window.dispatchEvent(new Event('crg:checkin-changed'));toast((c[who]?'Checked in: ':'Checked out: ')+who)});$('sheetContent')?.querySelectorAll('.crg-name-option').forEach(b=>b.addEventListener('click',()=>{$('crgPopupValue').value=b.dataset.name||''}, {once:false}));focus('crgPopupValue')}
function substitute(){const ns=(($('names')?.value)||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!ns.length)return toast('Add players first');open('Substitute player',`${field('crgPopupAbsent','Player leaving the session','')}${field('crgPopupReplacement','Replacement name','')}<p class="hint">Only the remaining games will be rebuilt. Completed/locked games stay fixed.</p>`,'Review substitution',host=>{const absent=($('crgPopupAbsent')?.value||'').trim(),replacement=($('crgPopupReplacement')?.value||'').trim();const real=ns.find(n=>n.toLowerCase()===absent.toLowerCase());if(!real){toast('Player not found');return}if(!replacement){$('crgPopupReplacement')?.focus();return}const rows=[...document.querySelectorAll('#scheduleList .game-row')];const idx=ns.indexOf(real);const affected=rows.filter(r=>{const t=r.querySelector('.game-match')?.innerText||'';return !r.classList.contains('done')&&t.toLowerCase().includes(real.toLowerCase())}).length;close();const sh=sheet();if(!sh)return;open('Confirm substitution',`<p class="hint"><b>${esc(real)}</b> → <b>${esc(replacement)}</b></p><p class="hint"><b>${affected} remaining game(s)</b> are affected.</p><p class="hint">Completed games and locked games remain fixed; only eligible remaining games are rebuilt.</p>`,'Confirm & rebuild',()=>{const next=ns.map(x=>x===real?replacement: x);$('names').value=next.join('\n');$('generateBtn')?.click();setTimeout(()=>{document.body.classList.remove('modal-open');window.dispatchEvent(new Event('crg:substitution-done'))},250)});});focus('crgPopupAbsent')}
function toast(text){let x=document.querySelector('.facility-toast');if(!x){x=document.createElement('div');x.className='facility-toast';document.body.appendChild(x)}x.textContent=text;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),2300)}
// Intercept facility buttons before their original onclick handlers can invoke prompt().
document.addEventListener('click',ev=>{const b=ev.target.closest?.('#fuName,#fuCheckin,#fuSubstitute');if(!b)return;ev.preventDefault();ev.stopImmediatePropagation();if(b.id==='fuName')nameSession();else if(b.id==='fuCheckin')checkin();else substitute()},true);
// Keep facility stats/tools fresh after modal-based actions.
window.addEventListener('crg:session-named',()=>{try{window.renderFacilityTools?.()}catch{}});
window.addEventListener('crg:checkin-changed',()=>{try{window.renderFacilityBusiness?.()}catch{}});
})();
