(()=>{'use strict';
const plans=[
 {name:'Free',price:'₱0',period:'/month',badge:'Try it out',target:'Casual players',features:['Single session max','12 players max','Basic rotation only','No save / export']},
 {name:'Pro',price:'₱149',period:'/month',annual:'₱1,499/year · save 17%',badge:'Best value',target:'Serious hobbyists, small groups',featured:true,features:['Unlimited sessions','24 players max','Save & resume sessions','Leaderboard tracking','PDF / CSV export','Skill level balancing','Player preferences','Mobile-optimized']},
 {name:'Business',price:'₱499',period:'/month',annual:'₱4,999/year · save 17%',badge:'Full suite',target:'Facility operators, leagues',features:['Everything in Pro','Multi-court management','Player database','Season / tournament management','Analytics dashboard','GCash / Maya payment integration ready','Attendance reports','API access','Email support','Recurring sessions','Display screen mode']},
 {name:'Enterprise',price:'₱2,499',period:'/month',badge:'Custom',target:'Multi-location chains',features:['White-label solution','Multiple facilities','Custom integrations','Dedicated support','Advanced analytics','Priority feature requests']}
];
const revenue=[['100 Pro users','₱1,788,000 / year'],['20 Business users','₱119,760 / year'],['2 Enterprise users','₱59,976 / year'],['Total','₱1,967,736 / year']];
function esc(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function render(){const old=document.getElementById('crgPricing');if(!old)return;const host=old.parentElement;if(!host)return;old.innerHTML=`<div class="card-head"><div><h3>Pricing</h3><p class="hint">Philippine Peso · simple plans for players, groups, and facilities.</p></div><span class="facility-pill">PHP pricing</span></div><div class="facility-pricing-grid">${plans.map(p=>`<article class="facility-plan ${p.featured?'featured':''}"><div class="facility-plan-top"><div><h3>${esc(p.name)}</h3><span class="facility-pill">${esc(p.badge)}</span></div><div class="facility-plan-price">${esc(p.price)}<span>${esc(p.period)}</span></div></div><p class="facility-plan-target"><b>${esc(p.target)}</b></p>${p.annual?`<div class="facility-plan-annual">${esc(p.annual)}</div>`:''}<div class="facility-plan-rule"></div><ul>${p.features.map(f=>`<li>✓ ${esc(f)}</li>`).join('')}</ul></article>`).join('')}</div><div class="facility-launch"><div><h3>🎁 Launch Offer</h3><p>First month free for early adopters who sign up before the end of the launch month.</p></div><div class="facility-launch-prices"><b>Pro: FREE</b><span>normally ₱149</span><b>Business: ₱249</b><span>normally ₱499 · 50% off</span></div></div><div class="facility-revenue"><div class="card-head"><h3>Projected first-year revenue</h3><span class="facility-pill">Illustrative</span></div><p class="hint">Based on the adoption example provided, using 12 months of billing.</p><div class="facility-revenue-grid">${revenue.map(r=>`<div class="facility-revenue-row"><span>${esc(r[0])}</span><b>${esc(r[1])}</b></div>`).join('')}</div></div><p class="facility-subtle">Payment methods planned for the PH market: GCash, Maya, Visa/Mastercard, BDO/BPI online banking, and 7-Eleven payment options, subject to the selected payment provider and integration setup.</p>`;}
function css(){if(document.getElementById('pricingUiStyle'))return;const s=document.createElement('style');s.id='pricingUiStyle';s.textContent=`.facility-pricing-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:14px}.facility-plan{border:1px solid var(--line,#26322b);border-radius:16px;padding:16px;background:rgba(255,255,255,.02)}.facility-plan.featured{box-shadow:0 0 0 1px rgba(120,220,150,.25);transform:translateY(-2px)}.facility-plan-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.facility-plan h3{margin:0 0 8px}.facility-plan-price{font-size:28px;font-weight:900;white-space:nowrap}.facility-plan-price span{font-size:12px;font-weight:700;opacity:.65}.facility-plan-target{min-height:36px}.facility-plan-annual,.facility-launch{border-radius:10px;padding:9px 10px;background:rgba(255,255,255,.04);font-size:12px;font-weight:800}.facility-plan-rule{height:1px;background:var(--line,#26322b);margin:12px 0}.facility-plan ul{margin:0;padding-left:0;list-style:none;display:grid;gap:7px;font-size:13px;line-height:1.35}.facility-launch{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-top:14px}.facility-launch-prices{display:grid;grid-template-columns:auto auto;gap:3px 12px;text-align:right}.facility-launch-prices span{opacity:.65;font-size:12px}.facility-revenue{margin-top:14px}.facility-revenue-grid{display:grid;gap:6px}.facility-revenue-row{display:flex;justify-content:space-between;border-bottom:1px solid var(--line,#26322b);padding:8px 0}.facility-revenue-row:last-child{border-bottom:0;font-size:15px}.facility-revenue-row:last-child b{font-size:18px}@media(max-width:1050px){.facility-pricing-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){.facility-pricing-grid{grid-template-columns:1fr}.facility-launch{display:block}.facility-launch-prices{text-align:left;margin-top:10px}.facility-revenue-row{gap:12px;align-items:center}}`;document.head.appendChild(s)}
function init(){css();render();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,400),{once:true});else setTimeout(init,400);
window.addEventListener('load',()=>setTimeout(init,100));
})();
