(()=>{'use strict';
const P='crg-pro-v2',SUPA_URL='https://tznozhempoeqrzjinuve.supabase.co',SUPA_KEY='sb_publishable_nvSlg3hOyIVYXNGhxZqh8A_GuXnb_Xj';
const $=id=>document.getElementById(id),wait=m=>new Promise(r=>setTimeout(r,m));
let undo=[],redo=[],before=null,applying=false,timerStart=Date.now(),paused=localStorage.getItem(P+':paused')==='1',history=JSON.parse(localStorage.getItem(P+':history')||'[]'),checkins=JSON.parse(localStorage.getItem(P+':checkins')||'{}'),recurring=JSON.parse(localStorage.getItem(P+':recurring')||'null');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function nms(){return($('names')?.value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function code(){const t=$('sessionCodeText')?.textContent||'',m=t.match(/CRG-[A-Z0-9]+/);return m?m[0]:null}
function snap(){const ns=nms(),mp=new Map(ns.map((n,i)=>[n,i+1])),rows=[...document.querySelectorAll('#scheduleList .game-row')];if(!rows.length)return null;return{names:ns,config:{courts:+($('courts')?.value||1),duration:+($('duration')?.value||15),sessionLength:+($('sessionLength')?.value||0)},games:rows.map(r=>{const l=(r.querySelector('.game-match')?.innerText||'').split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&x!=='VS'),tm=x=>x.split(/\s+\+\s+/).map(y=>mp.get(y)).filter(Boolean),h=[...r.querySelectorAll('.hint')].map(x=>x.innerText).find(x=>x.startsWith('Court '))||'',sit=(h.match(/Sitting:\s*(.*)$/)||[])[1]||'None',st=r.querySelector('.game-status')?.innerText||'';return{teams:[tm(l[0]||''),tm(l[1]||'')],court:+((h.match(/Court\s+(\d+)/)||[])[1]||1),sitting:sit==='None'?[]:sit.split(',').map(x=>mp.get(x.trim())).filter(Boolean),locked:r.classList.contains('locked'),result:st.includes('Team A won')?0:st.includes('Team B won')?1:null}}],scores:JSON.parse(localStorage.getItem('crg-pro-v1:scores')||'{}'),notes:JSON.parse(localStorage.getItem('crg-pro-v1:notes')||'{}'),at:Date.now()}}
function store(){localStorage.setItem(P+':history',JSON.stringify(history.slice(-100)));localStorage.setItem(P+':checkins',JSON.stringify(checkins));localStorage.setItem(P+':recurring',JSON.stringify(recurring))}
async function restore(s,stack){if(!s)return;if(stack)redo.push(snap());applying=true;window.__CRG_HYDRATE_GAMES=s.games.map(g=>({teams:g.teams,sitting:g.sitting,court:g.court}));$('names').value=s.names.join('\n');$('courts').value=s.config.courts;$('duration').value=s.config.duration;$('sessionLength').value=s.config.sessionLength||'';$('generateBtn')?.click();await wait(90);for(let i=0;i<s.games.length;i++){const g=s.games[i];if(g.result!==null&&g.result!==undefined){const b=document.querySelector(`#scheduleList [data-result=\"${i}\"]`);if(b){b.click();await wait(20);const w=document.querySelector(`[data-winner=\"${g.result}\"]`);w?.click();await wait(25)}}}for(let i=0;i<s.games.length;i++)if(s.games[i].locked){const b=document.querySelector(`#scheduleList [data-lock=\"${i}\"]`);if(b&&!b.closest('.game-row')?.classList.contains('locked'))b.click()}applying=false;render();}
function render(){const rows=[...document.querySelectorAll('#scheduleList .game-row')],scores=JSON.parse(localStorage.getItem('crg-pro-v1:scores')||'{}');rows.forEach((r,i)=>{r.querySelector('.crg-score')?.remove();if(scores[i]?.score){const d=document.createElement('div');d.className='crg-score crg-mini';d.textContent='Score: '+scores[i].score;r.querySelector('.game-status')?.parentElement.appendChild(d)}});const b=$('crgNoteList');if(b){const notes=JSON.parse(localStorage.getItem('crg-pro-v1:notes')||'{}');b.querySelectorAll('[data-note]').forEach(x=>x.value=notes[x.dataset.note]||'')}}
function timerUI(){let x=$('crgTimer');if(!x){x=document.createElement('div');x.id='crgTimer';x.className='crg-pro';x.innerHTML='<b>Game timer</b><span id="crgClock">15:00</span><button class="btn secondary" id="crgTimerBtn">Pause</button>';document.querySelector('#liveView .live-card')?.prepend(x);$('crgTimerBtn').onclick=()=>{paused=!paused;localStorage.setItem(P+':paused',paused?'1':'0');$('crgTimerBtn').textContent=paused?'Resume':'Pause'}}setInterval(()=>{const mins=+($('duration')?.value||15)*60,sec=Math.max(0,mins-(paused?Math.floor((Date.now()-timerStart)/1000):Math.floor((Date.now()-timerStart)/1000)));const left=Math.max(0,mins-sec);const m=Math.floor(left/60),s=String(left%60).padStart(2,'0');$('crgClock').textContent=m+':'+s;if(left===120&&Notification?.permission==='granted')new Notification('Court Rotation',{body:'Move to the next game in 2 minutes.'})},1000)}
function historyUI(){const m=$('moreView');if(!m||$('crgHistory'))return;const c=document.createElement('div');c.id='crgHistory';c.className='crg-pro';c.innerHTML='<div class="card-head"><h3>History & Leaderboard</h3><select id="crgFilter"><option value="all">All time</option><option value="week">This week</option><option value="month">This month</option><option value="season">Season</option></select></div><div id="crgHistoryList" class="crg-mini"></div><div class="crg-tools"><button class="btn secondary" id="crgCheckin">Player check-in</button><button class="btn secondary" id="crgRecurring">Recurring session</button></div>';m.querySelector('.tools-grid')?.append(c);$('crgFilter').onchange=historyUI.render;$('crgCheckin').onclick=()=>{const cde=code()||'SESSION',ns=nms();const old=checkins[cde]||{};const who=prompt('Player checking in:\n'+ns.join('\n'));if(!who)return;old[who]=!old[who];checkins[cde]=old;store();historyUI.render();toast((old[who]?'Checked in: ':'Checked out: ')+who);};$('crgRecurring').onclick=()=>{const day=prompt('Weekly day (e.g. Thursday):',recurring?.day||'Thursday');if(!day)return;const time=prompt('Time (e.g. 19:00):',recurring?.time||'19:00');if(!time)return;recurring={day,time,court:$('courts')?.value||1};store();toast('Recurring session saved')};historyUI.render()}
historyUI.render=()=>{const b=$('crgHistoryList');if(!b)return;const f=$('crgFilter')?.value||'all',cut=f==='week'?Date.now()-604800000:f==='month'?Date.now()-2592000000:f==='season'?Date.now()-7776000000:0;const agg={};history.filter(x=>x.at>=cut).forEach(x=>Object.entries(x.totals||{}).forEach(([n,v])=>{agg[n]??={w:0,l:0};agg[n].w+=v.w||0;agg[n].l+=v.l||0}));b.innerHTML=Object.entries(agg).sort((a,b)=>(b[1].w-a[1].w)||(a[0].localeCompare(b[0]))).map(([n,v],i)=>`<div>#${i+1} ${esc(n)} — ${v.w}W-${v.l}L</div>`).join('')||'No saved history yet.'}
function saveHistory(){const s=snap();if(!s)return;const totals={},ns=s.names;s.games.forEach(g=>{if(g.result===null||g.result===undefined)return;for(const id of g.teams[g.result]||[]){const n=ns[id-1];totals[n]??={w:0,l:0};totals[n].w++}for(const id of g.teams[1-g.result]||[]){const n=ns[id-1];totals[n]??={w:0,l:0};totals[n].l++}});history.push({at:Date.now(),code:code(),totals});store();historyUI.render()}
function toast(t){let x=document.querySelector('.crg-toast');if(!x){x=document.createElement('div');x.className='crg-toast';document.body.appendChild(x)}x.textContent=t;clearTimeout(x.t);x.t=setTimeout(()=>x.remove(),2000)}
function hook(){document.addEventListener('click',e=>{const t=e.target.closest?.('[data-lock],[data-result],#shuffleBtn,#rebuildBtn,#generateBtn,#nextBtn,#completeBtn');if(!t)return;if(!applying&&!t.matches('[data-result]'))before=snap();if(t.matches('[data-result]'))return;setTimeout(()=>{if(applying)return;const now=snap();if(before&&now){undo.push(before);redo=[]}saveHistory()},120)},true);document.addEventListener('visibilitychange',()=>{if(document.hidden)return;timerStart=Date.now()});}
function boot(){timerUI();historyUI();hook();new MutationObserver(()=>render()).observe(document.body,{subtree:true,childList:true});$('crgUndo')&&( $('crgUndo').onclick=async()=>{const s=undo.pop();if(s)await restore(s,true)});$('crgRedo')&&( $('crgRedo').onclick=async()=>{const s=redo.pop();if(s)await restore(s,false)});if(Notification&&Notification.permission==='default')Notification.requestPermission().catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();