(()=>{'use strict';
const P='crg-safe-v1';
const $=id=>document.getElementById(id);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let timerId=0,timerStart=Date.now(),paused=localStorage.getItem(P+':paused')==='1',history=read(P+':history',[]),checkins=read(P+':checkins',{}),recurring=read(P+':recurring',null);
let undo=[],redo=[],busy=false,lastHistoryKey='';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function names(){return(($('names')?.value)||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function toast(t){let x=document.querySelector('.crg-safe-toast');if(!x){x=document.createElement('div');x.className='crg-safe-toast';x.style.cssText='position:fixed;left:50%;bottom:90px;transform:translateX(-50%);z-index:9999;padding:10px 14px;border-radius:12px;background:#111;color:#fff;font-weight:800;box-shadow:0 10px 30px rgba(0,0,0,.3)';document.body.appendChild(x)}x.textContent=t;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),2200)}
function currentCode(){const t=$('sessionCodeText')?.textContent||'';return(t.match(/CRG-[A-Z0-9]+/)||[])[0]||'CRG-LOCAL'}
function snapshot(){const rows=[...document.querySelectorAll('#scheduleList .game-row')];if(!rows.length)return null;const ns=names(),map=new Map(ns.map((n,i)=>[n,i+1]));return{names:ns,config:{courts:+($('courts')?.value||1),duration:+($('duration')?.value||15),sessionLength:+($('sessionLength')?.value||0)},games:rows.map((r,i)=>{const lines=(r.querySelector('.game-match')?.innerText||'').split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&x!=='VS');const tm=x=>x.split(/\s+\+\s+/).map(y=>map.get(y)).filter(Boolean);const hint=[...r.querySelectorAll('.hint')].map(x=>x.innerText).find(x=>x.startsWith('Court '))||'';const sit=(hint.match(/Sitting:\s*(.*)$/)||[])[1]||'None';const st=r.querySelector('.game-status')?.innerText||'';return{teams:[tm(lines[0]||''),tm(lines[1]||'')],court:+((hint.match(/Court\s+(\d+)/)||[])[1]||1),sitting:sit==='None'?[]:sit.split(',').map(x=>map.get(x.trim())).filter(Boolean),locked:r.classList.contains('locked'),result:st.includes('Team A won')?0:st.includes('Team B won')?1:null}}]}
function restore(s){if(!s?.games?.length||busy)return;busy=true;window.__CRG_HYDRATE_GAMES=s.games.map(g=>({teams:g.teams.map(t=>t.slice()),sitting:g.sitting||[],court:g.court||1}));$('names').value=s.names.join('\n');$('courts').value=s.config?.courts||1;$('duration').value=s.config?.duration||15;$('sessionLength').value=s.config?.sessionLength||'';window.__CRG_INTERNAL=true;$('generateBtn')?.click();setTimeout(()=>{applyResults(s).finally(()=>{window.__CRG_INTERNAL=false;busy=false;toast('Session restored')})},120)}
async function applyResults(s){for(let i=0;i<s.games.length;i++){const g=s.games[i];if(g.result===null||g.result===undefined)continue;const b=document.querySelector(`#scheduleList [data-result="${i}"]`);if(!b)continue;b.click();await new Promise(r=>setTimeout(r,15));document.querySelector(`[data-winner="${g.result}"]`)?.click();await new Promise(r=>setTimeout(r,20))}for(let i=0;i<s.games.length;i++)if(s.games[i].locked){const b=document.querySelector(`#scheduleList [data-lock="${i}"]`);if(b&&!b.closest('.game-row')?.classList.contains('locked'))b.click()}}
function renderTimer(){let x=$('crgSafeTimer');if(!x){x=document.createElement('div');x.id='crgSafeTimer';x.className='crg-pro';x.innerHTML='<div class="card-head"><b>Game timer</b><span id="crgSafeClock">15:00</span></div><div class="crg-tools"><button class="btn secondary" id="crgSafePause">Pause</button><button class="btn secondary" id="crgSafeResetTimer">Reset timer</button></div>';document.querySelector('#liveView .live-card')?.prepend(x);$('crgSafePause').onclick=()=>{paused=!paused;localStorage.setItem(P+':paused',paused?'1':'0');timerStart=Date.now();$('crgSafePause').textContent=paused?'Resume':'Pause'}}if(timerId)clearInterval(timerId);timerId=setInterval(()=>{const total=Math.max(1,+($('duration')?.value||15))*60;const elapsed=paused?0:Math.max(0,Math.floor((Date.now()-timerStart)/1000));const left=Math.max(0,total-elapsed);if($('crgSafeClock'))$('crgSafeClock').textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0')},1000);$('crgSafeResetTimer')?.addEventListener('click',()=>{timerStart=Date.now();paused=false;localStorage.setItem(P+':paused','0');if($('crgSafePause'))$('crgSafePause').textContent='Pause';toast('Timer reset')},{once:true})}
function recordHistory(){const s=snapshot();if(!s)return;const key=JSON.stringify(s.games.map(g=>g.result));if(key===lastHistoryKey)return;lastHistoryKey=key;const totals={};s.games.forEach(g=>{if(g.result===null||g.result===undefined)return;(g.teams[g.result]||[]).forEach(id=>{const n=s.names[id-1];totals[n]??={w:0,l:0};totals[n].w++});(g.teams[1-g.result]||[]).forEach(id=>{const n=s.names[id-1];totals[n]??={w:0,l:0};totals[n].l++})});if(Object.keys(totals).length){history.push({at:Date.now(),code:currentCode(),totals});history=history.slice(-100);write(P+':history',history)}}
function historyUI(){const m=$('moreView');if(!m||$('crgSafeHistory'))return;const c=document.createElement('div');c.id='crgSafeHistory';c.className='card';c.innerHTML='<div class="card-head"><h3>History & Facility</h3><span class="hint">Safe mode</span></div><div id="crgSafeHistoryList" class="hint"></div><div class="crg-tools"><button class="btn secondary" id="crgSafeCheckin">Check-in player</button><button class="btn secondary" id="crgSafeRecurring">Recurring session</button><button class="btn secondary" id="crgSafeUndo">↶ Undo</button><button class="btn secondary" id="crgSafeRedo">↷ Redo</button></div>';m.querySelector('.tools-grid')?.appendChild(c);$('crgSafeCheckin').onclick=()=>{const n=prompt('Player checking in:\n'+names().join('\n'));if(!n)return;checkins[n]=!checkins[n];write(P+':checkins',checkins);renderHistoryList();toast((checkins[n]?'Checked in: ':'Checked out: ')+n)};$('crgSafeRecurring').onclick=()=>{const day=prompt('Weekly day:',recurring?.day||'Thursday');if(!day)return;const time=prompt('Time:',recurring?.time||'19:00');if(!time)return;recurring={day,time,courts:+($('courts')?.value||1)};write(P+':recurring',recurring);toast('Recurring session saved')};$('crgSafeUndo').onclick=()=>{const s=undo.pop();if(!s)return;const now=snapshot();if(now)redo.push(now);restore(s)};$('crgSafeRedo').onclick=()=>{const s=redo.pop();if(!s)return;const now=snapshot();if(now)undo.push(now);restore(s)};renderHistoryList()}
function renderHistoryList(){const b=$('crgSafeHistoryList');if(!b)return;const totals={};history.forEach(h=>Object.entries(h.totals||{}).forEach(([n,v])=>{totals[n]??={w:0,l:0};totals[n].w+=v.w||0;totals[n].l+=v.l||0}));b.innerHTML=Object.entries(totals).sort((a,b)=>(b[1].w-a[1].w)||a[0].localeCompare(b[0])).map(([n,v],i)=>`<div>#${i+1} ${esc(n)} — ${v.w}W-${v.l}L</div>`).join('')||'No completed games saved yet.'}
function hook(){document.addEventListener('click',e=>{const t=e.target.closest?.('#generateBtn,#nextBtn,#completeBtn,#rebuildBtn,#shuffleBtn,[data-lock],[data-result]');if(!t||window.__CRG_INTERNAL)return;if(!t.matches('[data-result]')){const before=snapshot();setTimeout(()=>{const after=snapshot();if(before&&after){undo.push(before);redo=[]}recordHistory();write(P+':last',after)},180)}else{setTimeout(recordHistory,100)}} ,true);document.addEventListener('input',e=>{if(e.target?.id==='names'||e.target?.id==='courts'||e.target?.id==='duration'||e.target?.id==='sessionLength')setTimeout(()=>write(P+':draft',{names:e.target?.id==='names'?e.target.value:$('names')?.value||'',courts:$('courts')?.value||1,duration:$('duration')?.value||15,sessionLength:$('sessionLength')?.value||''}),0)});}
function boot(){try{renderTimer();historyUI();hook();const saved=read(P+':session',null);if(saved&&saved.games?.length&&!location.hash.startsWith('#snapshot='))setTimeout(()=>{const ok=confirm('Resume your last saved court session?');if(ok)restore(saved)},300)}catch(err){console.error('CRG safe boot failed',err)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();