(function(){'use strict';
function seeded(seed){let x=seed>>>0;return function(){x+=0x6D2B79F5;let t=x;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function quad(a){return a.slice().sort((x,y)=>x-y).join('-')}
function combos(a){let out=[];for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)for(let k=j+1;k<a.length;k++)for(let l=k+1;l<a.length;l++)out.push([a[i],a[j],a[k],a[l]]);return out}
const skillValue=v=>{if(typeof v==='number')return Math.max(1,Math.min(5,v));const s=String(v||'').toLowerCase();if(s==='beginner')return 1;if(s==='advanced')return 5;if(s==='intermediate')return 3;const n=Number(s);return Number.isFinite(n)?Math.max(1,Math.min(5,n)):3};
function score(games,players,skills){let partner=new Map(players.map(p=>[p,new Set()])),opp=new Map(players.map(p=>[p,new Map()])),sits=new Map(players.map(p=>[p,0])),last=new Map(players.map(p=>[p,0])),quads=new Map(),rp=0,ro=0,rq=0,skillPenalty=0;games.forEach(g=>{let on=g.teams.flat(),q=quad(on);quads.set(q,(quads.get(q)||0)+1);on.forEach(p=>last.set(p,0));g.sitting.forEach(p=>{if(last.get(p))sits.set(p,sits.get(p)+1);last.set(p,last.get(p)+1)});g.teams.forEach(([a,b])=>{if(partner.get(a).has(b))rp++;partner.get(a).add(b);partner.get(b).add(a);skillPenalty+=Math.abs(skillValue(skills.get(a))-skillValue(skills.get(b)))});let[a,b]=g.teams;for(let x of a)for(let y of b){if(opp.get(x).has(y))ro++;opp.get(x).set(y,(opp.get(x).get(y)||0)+1);opp.get(y).set(x,(opp.get(y).get(x)||0)+1)}});quads.forEach(v=>{if(v>1)rq+=v-1});let sv=[...sits.values()],spread=sv.length?Math.max(...sv)-Math.min(...sv):0;return Math.max(0,Math.min(100,Math.round(100-rp*35-ro*5-rq*18-spread*12-skillPenalty*2)))}
function generate(cfg){let players=cfg.players.slice(),fixed=cfg.fixed||new Map(),requestedPer=Math.max(1,Number(cfg.per)||1),total=Number.isInteger(cfg.totalGames)?cfg.totalGames:Math.max(1,Math.floor(players.length*requestedPer/4)),targets=new Map(cfg.targets instanceof Map?cfg.targets:players.map(p=>[p,requestedPer]));
if(fixed.size){for(const g of fixed.values())for(const p of g.teams.flat())targets.set(p,(targets.get(p)||0)+1)}
if(players.length<4||total<1)return null;let participant=[...new Set([...players,...[...fixed.values()].flatMap(g=>g.teams.flat())])],best=null;
const attempts=Math.max(1,Math.min(120,Number(cfg.attempts)||60)),maxEligible=Math.min(16,players.length),maxChoices=120;
const budgetMs=Math.max(250,Math.min(1800,Number(cfg.timeBudgetMs)||1200)),deadline=(typeof performance!=='undefined'&&performance.now?performance.now():Date.now())+budgetMs;
const timedOut=()=>((typeof performance!=='undefined'&&performance.now?performance.now():Date.now())>=deadline);
const skills=cfg.skills instanceof Map?cfg.skills:new Map(Object.entries(cfg.skills||window.CRG_PLAYER_SKILLS||{}));const skillScore=new Map(participant.map(p=>[p,skillValue(skills.get(p))]));const skillOf=p=>skillScore.get(p)||3;
// Hard outer-loop guard: the counter is checked before any attempt work, independently of the time budget.
let hardIterationCount=0;
for(let attempt=0;attempt<attempts;attempt++){if(++hardIterationCount>attempts||timedOut())break;let r=seeded(((cfg.seed||0)+attempt*7919)>>>0),plays=new Map(participant.map(p=>[p,0])),partners=new Map(participant.map(p=>[p,new Set()])),opps=new Map(participant.map(p=>[p,new Map()])),last=new Map(players.map(p=>[p,0])),quads=new Map(),games=new Array(total),ok=true;
function add(g){let on=g.teams.flat(),u=new Set(on);if(on.length!==4||u.size!==4||on.some(p=>!plays.has(p)))return false;for(const[t1,t2]of g.teams){let ta=targets.get(t1)||0,tb=targets.get(t2)||0;if(partners.get(t1).has(t2)||plays.get(t1)>=ta||plays.get(t2)>=tb)return false}let q=quad(on);if((quads.get(q)||0)>=2)return false;g.sitting=players.filter(p=>!u.has(p));g.teams.forEach(([a,b])=>{partners.get(a).add(b);partners.get(b).add(a);plays.set(a,plays.get(a)+1);plays.set(b,plays.get(b)+1)});let[a1,a2]=g.teams[0],[b1,b2]=g.teams[1];[[a1,b1],[a1,b2],[a2,b1],[a2,b2]].forEach(([a,b])=>{opps.get(a).set(b,(opps.get(a).get(b)||0)+1);opps.get(b).set(a,(opps.get(b).get(a)||0)+1)});quads.set(q,(quads.get(q)||0)+1);players.forEach(p=>last.set(p,u.has(p)?0:(last.get(p)||0)+1));return true}
for(let i=0;i<total;i++){if(timedOut()){ok=false;break}let fx=fixed.get(i);if(fx){let copy={teams:fx.teams.map(t=>t.slice()),sitting:fx.sitting.slice(),court:fx.court||((i%cfg.courts)+1)};if(!add(copy)){ok=false;break}games[i]=copy;continue}let eligible=shuffle(players.filter(p=>plays.get(p)<(targets.get(p)||0)),r).sort((a,b)=>((plays.get(a)-plays.get(b))*5)+((last.get(a)||0)-(last.get(b)||0))*2+(r()-.5));let choices=shuffle(combos(eligible.slice(0,Math.min(maxEligible,eligible.length))),r).slice(0,maxChoices),chosen=null,localBest=-Infinity;for(let four of choices){if(timedOut()){ok=false;break}let q=quad(four),splits=shuffle([[[four[0],four[1]],[four[2],four[3]]],[[four[0],four[2]],[four[1],four[3]]],[[four[0],four[3]],[four[1],four[2]]]],r);const skills4=four.map(skillOf);for(let[t1,t2]of splits){if(timedOut()){ok=false;break}if(partners.get(t1[0]).has(t1[1])||partners.get(t2[0]).has(t2[1]))continue;let local=(quads.get(q)||0)*-50;four.forEach(p=>{local-=plays.get(p)*6;if(last.get(p)>0)local+=cfg.rest==='avoid-consecutive'?12:3});for(let x of t1)for(let y of t2)if(opps.get(x).has(y))local-=16*(opps.get(x).get(y)||1);const gap1=Math.abs(skills4[0]-skills4[1]),gap2=Math.abs(skills4[2]-skills4[3]),teamGap=Math.abs((skills4[0]+skills4[1])-(skills4[2]+skills4[3]));local-=gap1*7+gap2*7+teamGap*3;if(gap1===0)local+=3;if(gap2===0)local+=3;if(local>localBest){localBest=local;chosen={teams:[t1.slice(),t2.slice()]}}}}
if(!ok)break;if(!chosen||!add(chosen)){ok=false;break}chosen.court=(i%cfg.courts)+1;games[i]=chosen}if(!ok)continue;let sc=score(games,players,skills);if(!best||sc>best.score)best={games,score:sc};if(sc>=98)break}
return best}
window.RotationScheduler={generate,skillValue};})();