(()=>{'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=s=>String(s??'').trim().toLocaleLowerCase().replace(/(^|[\s'-])([a-zà-ÿ])/g,(_,p,c)=>p+c.toLocaleUpperCase());
function openSheet(html){const sheet=$('sheet'),content=$('sheetContent');if(!sheet||!content)return;content.innerHTML=html;sheet.hidden=false}
function closeSheet(){const sheet=$('sheet');if(sheet)sheet.hidden=true}
function rankingsHtml(){const rows=[...document.querySelectorAll('#rankingsList .rank-row')];if(!rows.length)return '<div class="empty">No completed games were recorded.</div>';return `<div class="complete-rankings">${rows.map((r,i)=>{const name=r.querySelector('.rank-name')?.textContent?.trim()||'Player';const rec=r.querySelector('.rank-record')?.textContent?.trim()||'';const pct=r.querySelector('.rank-pct')?.firstChild?.textContent?.trim()||'';const place=i<5?`${i+1}${i===0?'st':i===1?'nd':i===2?'rd':'th'}`:`${i+1}th`;return `<div class="complete-rank-row ${i<5?'top-five':'rest-rank'}"><span class="complete-place">${esc(place)}</span><span class="complete-name">${esc(name)}</span><span class="complete-record">${esc(rec)}</span><span class="complete-pct">${esc(pct)}</span></div>`}).join('')}</div>`}
function showCompletion(){openSheet(`<div class="sheet-title">🏆 Session complete</div><p class="hint">All scheduled games are finished. Final rankings</p><div class="completion-rankings-wrap">${rankingsHtml()}</div><button class="btn full complete-close" type="button">Done</button>`);document.querySelector('.complete-close')?.addEventListener('click',closeSheet)}
function checkComplete(){setTimeout(()=>{if($('currentNo')?.textContent.includes('SESSION COMPLETE'))showCompletion()},80)}
function confirmAction(kind,button){const restart=kind==='restart';openSheet(`<div class="sheet-title">${restart?'Restart live session?':'Reset everything?'}</div><p class="hint">${restart?'This clears recorded winners and starts the current rotation again from Game 1. Players and the schedule stay.':'This clears the current rotation, results, and player list. This cannot be undone.'}</p><div class="confirm-actions"><button class="btn secondary" type="button" data-cancel-confirm>Cancel</button><button class="btn ${restart?'':'danger'}" type="button" data-confirm-action>${restart?'Restart session':'Reset everything'}</button></div>`);document.querySelector('[data-cancel-confirm]')?.addEventListener('click',closeSheet);document.querySelector('[data-confirm-action]')?.addEventListener('click',()=>{closeSheet();button.dataset.allowClick='1';button.click()})}
function preparePrint(){document.getElementById('printReport')?.remove();const names=[...document.querySelectorAll('#playersView .player-card h3')].map(x=>x.textContent.trim()).filter(Boolean);const games=[...document.querySelectorAll('#scheduleList .game-row')];const report=document.createElement('section');report.id='printReport';report.innerHTML=`<header><h1>Court Rotation Schedule</h1><p>${names.length} players · ${games.length} games</p></header><section><h2>Players</h2><ol>${names.map(n=>`<li>${esc(n)}</li>`).join('')}</ol></section><section><h2>Schedule</h2><div>${games.map((g,i)=>{const label=g.querySelector('.game-label')?.textContent||`G${i+1}`;const match=g.querySelector('.game-match')?.innerHTML||'';const hints=[...g.querySelectorAll('.hint')].map(x=>x.textContent.trim()).filter(Boolean);return `<article><b>${esc(label)}</b><div>${match}</div><small>${esc(hints[hints.length-1]||'')}</small></article>`}).join('')}</div></section>`;document.body.appendChild(report);window.addEventListener('afterprint',()=>report.remove(),{once:true});window.print();setTimeout(()=>report.remove(),1000)}
function wire(){document.addEventListener('click',event=>{const t=event.target instanceof Element?event.target:null;if(!t)return;
if(t.id==='usePaste'){setTimeout(()=>{const input=$('sheetPaste'),names=$('names');if(input&&names){const v=input.value.split(/\r?\n/).map(title).filter(Boolean).join('\n');input.value=v;names.value=v;names.dispatchEvent(new Event('input',{bubbles:true}))}},0);return}
if(t.id==='restartBtn'&&!t.dataset.allowClick){event.preventDefault();event.stopImmediatePropagation();confirmAction('restart',t);return}
if(t.id==='resetBtn'&&!t.dataset.allowClick){event.preventDefault();event.stopImmediatePropagation();confirmAction('reset',t);return}
if(t.id==='restartBtn'&&t.dataset.allowClick)t.dataset.allowClick='';
if(t.id==='resetBtn'&&t.dataset.allowClick)t.dataset.allowClick='';
if(t.id==='printBtn'){event.preventDefault();event.stopImmediatePropagation();preparePrint();return}
if(t.id==='completeBtn'){setTimeout(()=>{if($('currentNo')?.textContent.includes('SESSION COMPLETE'))showCompletion()},40)}
},true)}
wire();
})();