(()=>{'use strict';
const CONFIG=window.CRG_SUPABASE_CONFIG||{};
const HISTORY_KEY='crg-spectator-history-v1';
const $=id=>document.getElementById(id);
const clean=v=>String(v??'').trim();
const title=v=>String(v??'').trim().replace(/\s+/g,' ').replace(/(^|[\s'-])([a-zà-ÿ])/g,(_,p,c)=>p+c.toLocaleUpperCase());
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const text=el=>el?.innerText?.trim()||'';
const code=()=>($('sessionCodeText')?.textContent||'').match(/CRG-[A-Z0-9]+/)?.[0]||'';
const valid=t=>Array.isArray(t)&&t.length===2&&t.every(team=>Array.isArray(team)&&team.length>=2&&team.every(p=>p&&clean(p.name)));
const storedSkills=()=>{try{return JSON.parse(localStorage.getItem('crg-skills-v1')||'{}')||{}}catch{return{}}};
const skillFor=(name,map)=>title(map[clean(name).toLocaleLowerCase()]||'Intermediate');
const skillMap=()=>{const names=($('names')?.value||'').split(/\r?\n/).map(clean).filter(Boolean).map(title),src=window.CRG_PLAYER_SKILLS||{},stored=storedSkills(),map={};names.forEach((n,i)=>map[n.toLocaleLowerCase()]=title(src[i+1]||stored[n]||'Intermediate'));return map};
function historyRead(c){try{return JSON.parse(localStorage.getItem(`${HISTORY_KEY}:${c}`)||'{}')||{}}catch{return{}}}
function historyWrite(c,h){try{localStorage.setItem(`${HISTORY_KEY}:${c}`,JSON.stringify(h))}catch{}}
function currentTeams(){const root=$('currentTeams'),map=skillMap();if(!root)return[[],[]];const blocks=[...root.querySelectorAll(':scope > .team')];if(blocks.length>=2){const out=blocks.slice(0,2).map(team=>[...team.querySelectorAll('.live-player')].map(p=>{const n=clean(p.querySelector('.live-player-name')?.textContent);return{name:n,skill:skillFor(n,map)}}).filter(p=>p.name));if(valid(out))return out}const raw=root.textContent.replace(/\s+/g,' ').trim(),parts=raw.split(/\s+VS\s+/i);if(parts.length!==2)return[[],[]];return parts.map(side=>side.split(/\s*\+\s*/).map(n=>({name:clean(n),skill:skillFor(n,map)})).filter(p=>p.name))}
function parseMatch(r){const match=r?.querySelector('.game-match');if(!match)return[[],[]];const direct=[...match.querySelectorAll(':scope > .schedule-team-players')].map(text).filter(Boolean);if(direct.length>=2)return direct.slice(0,2).map(s=>s.split(/\s*\+\s*/).map(n=>({name:clean(n),skill:skillFor(n,skillMap())})).filter(p=>p.name));const nodes=[...match.querySelectorAll(':scope > *')].map(text).filter(x=>x&& !/^(TEAM A|TEAM B|VS)$/i.test(x));if(nodes.length>=2)return nodes.slice(0,2).map(s=>s.split(/\s*\+\s*/).map(n=>({name:clean(n),skill:skillFor(n,skillMap())})).filter(p=>p.name));const raw=text(match).replace(/\s+/g,' ').trim(),parts=raw.split(/\s+VS\s+/i);if(parts.length!==2)return[[],[]];return parts.map(s=>s.split(/\s*\+\s*/).map(n=>({name:clean(n),skill:skillFor(n,skillMap())})).filter(p=>p.name))}
function winnerFromStatus(status){const s=String(status||'').toUpperCase();return s.includes('TEAM A WON')?0:s.includes('TEAM B WON')?1:null}
function buildPayload(){const c=code();if(!c)return null;const h=historyRead(c);const currentNo=Number((text($('currentNo')).match(/\d+/)||[])[0])||0;const ct=currentTeams();if(currentNo&&valid(ct)){h[currentNo]=ct;historyWrite(c,h)}const map=skillMap(),rows=[...document.querySelectorAll('#scheduleList .game-row')].map((r,i)=>{let teams=parseMatch(r);if(!valid(teams))teams=h[i+1]||[[],[]];else h[i+1]=teams;const status=text(r.querySelector('.game-status')),court=(text(r.querySelector('.hint')).match(/Court\s+(\d+)/i)||[])[1]||'1',winner=winnerFromStatus(status);return{index:i+1,teams,court,status,done:r.classList.contains('done'),locked:r.classList.contains('locked'),winner}});historyWrite(c,h);const rankings=[...document.querySelectorAll('#rankingsList .rank-row')].map(r=>({position:text(r.querySelector('.rank-pos')),name:text(r.querySelector('.rank-name')),record:text(r.querySelector('.rank-record')),winRate:text(r.querySelector('.rank-pct'))}));return{version:5,sessionCode:c,season:localStorage.getItem('crg-season-name')||'Court Rotation',current:{game:text($('currentNo')),court:text($('currentCourt')),teams:ct,sitting:text($('currentSit')),status:text($('liveStatus'))},progress:{text:text($('progressText')),percent:text($('progressPct'))},schedule:rows,rankings,updatedAt:new Date().toISOString()}}
let sbPromise;
async function db(){if(sbPromise)return sbPromise;const key=CONFIG.publishableKey||'';if(!CONFIG.url||!key)return null;sbPromise=(async()=>{if(!window.supabase?.createClient){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}return window.supabase?.createClient?window.supabase.createClient(CONFIG.url,key):null})();return sbPromise}
let timer=0,publishing=false;async function publish(){if(publishing)return;const payload=buildPayload();if(!payload)return;const client=await db();if(!client)return;publishing=true;try{await client.from('court_rotation_sessions').upsert({session_code:payload.sessionCode,payload,updated_at:payload.updatedAt},{onConflict:'session_code'})}finally{publishing=false}}
function queue(){clearTimeout(timer);timer=setTimeout(publish,650)}
function polish(){if(!document.body.classList.contains('spectator-mode'))return;const app=document.querySelector('.app');if(!app)return;const h1=app.querySelector('main > .card > h1');if(h1)h1.classList.add('spectator-main-title');const current=app.querySelector('.spectator-current');if(!current)return;const schedule=current.nextElementSibling;if(schedule)schedule.classList.add('spectator-schedule');const cards=schedule?.querySelectorAll(':scope > .spectator-game')||[];cards.forEach(card=>{const status=card.querySelector('.hint');if(!status)return;const raw=status.textContent||'',winner=/TEAM A WON/i.test(raw)?card.querySelector('.spectator-team'): /TEAM B WON/i.test(raw)?card.querySelectorAll('.spectator-team')[1]:null;if(winner){const names=[...winner.querySelectorAll('.spectator-player-name')].map(text).filter(Boolean);if(names.length>=2)status.textContent=`🏆 ${names.join(' + ')} won`}});const leaderboard=schedule?.nextElementSibling;if(leaderboard?.querySelector('h2')?.textContent.trim().toLowerCase()==='leaderboard')leaderboard.classList.add('spectator-leaderboard')}
function injectStyle(){if(document.getElementById('spectatorFixStyles'))return;const s=document.createElement('style');s.id='spectatorFixStyles';s.textContent='.spectator-main-title{text-align:center!important}.spectator-schedule{display:grid!important;gap:var(--section-gap,16px)!important;margin-top:var(--section-gap,16px)!important}.spectator-game{margin:0!important}.spectator-leaderboard{display:grid;gap:var(--section-gap,16px)!important}.spectator-leaderboard .rank-row{margin:0!important}.spectator-schedule + .spectator-leaderboard{margin-top:var(--section-gap,16px)!important}.spectator-game .hint{margin-top:0}';document.head.appendChild(s)}
function boot(){injectStyle();const spectator=new URLSearchParams(location.search).get('view')==='spectator';if(spectator){polish();new MutationObserver(()=>polish()).observe(document.body,{subtree:true,childList:true,characterData:true});return}new MutationObserver(queue).observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','style']});queue()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();