const fs=require('node:fs');const vm=require('node:vm');const {performance}=require('node:perf_hooks');const {test,expect}=require('@playwright/test');
function loadScheduler(){const source=fs.readFileSync('scheduler.js','utf8');const sandbox={window:{},performance,Date,Math,Set,Map,Number,String,Object,Array};vm.createContext(sandbox);vm.runInContext(source,sandbox,{timeout:10000});return sandbox.window.RotationScheduler;}
function cfg(players,courts,per=3,extra={}){return{players,per,targets:new Map(players.map(p=>[p,per])),courts,rest:'balanced',seed:123,skills:new Map(),attempts:120,...extra}}
function slotRoundDisjoint(games,courts){for(let i=0;i<games.length;i+=courts){const seen=new Set();for(let j=i;j<Math.min(i+courts,games.length);j++){for(const p of games[j].teams.flat()){if(seen.has(p))return false;seen.add(p)}}}return true}
function attendance(games,players){const counts=new Map(players.map(p=>[p,0]));for(const g of games)for(const p of g.teams.flat())counts.set(p,(counts.get(p)||0)+1);return counts}
function overlaps(a,b){const s=new Set(a.teams.flat());return b.teams.flat().some(p=>s.has(p))}
test('parallel-safe scheduler matrix is complete and disjoint',()=>{const s=loadScheduler();for(const playersCount of [8,9,12,13,16])for(const courts of [1,2,3,4])for(const seed of [101,202,303]){const players=Array.from({length:playersCount},(_,i)=>i+1),r=s.generate(cfg(players,courts,3,{seed}));expect(r,JSON.stringify({playersCount,courts,seed})).toBeTruthy();expect(r.requestedCourts).toBe(courts);expect(r.effectiveCourts).toBe(Math.min(courts,Math.floor(playersCount/4)));expect(r.games).toHaveLength(Math.floor(playersCount*3/4));expect(slotRoundDisjoint(r.games,r.effectiveCourts)).toBeTruthy();const a=[...attendance(r.games,players).values()];expect(Math.min(...a)).toBeGreaterThanOrEqual(Math.floor(r.games.length*4/playersCount));expect(Math.max(...a)).toBeLessThanOrEqual(Math.ceil(r.games.length*4/playersCount));expect(Math.max(...a)).toBeLessThanOrEqual(3);}});
test('fixed games keep teams, court, and round while new games avoid non-done fixed players',()=>{const s=loadScheduler(),players=Array.from({length:12},(_,i)=>i+1),base=s.generate(cfg(players,3,3,{seed:4242})),indexes=[0,4,6],fixed=new Map(indexes.map(i=>[i,{teams:base.games[i].teams.map(t=>t.slice()),sitting:(base.games[i].sitting||[]).slice(),court:base.games[i].court,round:Math.floor(i/3)}])),r=s.generate(cfg(players,3,3,{seed:4242,fixed}));expect(r).toBeTruthy();for(const i of indexes){expect(r.games[i].teams).toEqual(fixed.get(i).teams);expect(r.games[i].court).toBe(fixed.get(i).court);expect(r.games[i].round).toBe(fixed.get(i).round)}for(let i=0;i<r.games.length;i++){if(fixed.has(i))continue;const slot=Math.floor(i/r.effectiveCourts),blocked=[...fixed.entries()].filter(([fi])=>Math.floor(fi/r.effectiveCourts)===slot).flatMap(([,fx])=>fx.teams.flat());expect(r.games[i].teams.flat().some(p=>blocked.includes(p))).toBeFalsy()}const maxFixed=Math.max(...[...fixed.values()].map(g=>g.round));expect(r.games.filter((_,i)=>!fixed.has(i)).every(g=>g.round>maxFixed)).toBeTruthy();});
test('done fixed games do not block new games',()=>{const s=loadScheduler(),players=Array.from({length:12},(_,i)=>i+1),base=s.generate(cfg(players,3,3,{seed:4242})),fx=base.games[2],fixed=new Map([[2,{teams:fx.teams.map(t=>t.slice()),sitting:(fx.sitting||[]).slice(),court:fx.court,round:0,done:true}]]),r=s.generate(cfg(players,3,3,{seed:42,fixed}));expect(r).toBeTruthy();expect([0,1].some(i=>overlaps(fx,r.games[i]))).toBeTruthy();});
test('departed player in fixed game does not throw and reduces effective courts',()=>{const s=loadScheduler(),players=Array.from({length:11},(_,i)=>i+1),fixed=new Map([[0,{teams:[[1,12],[2,3]],sitting:[4,5,6,7,8,9,10,11],court:1,round:0}]]),r=s.generate({players,per:3,totalGames:9,targets:new Map(players.map(p=>[p,3])),courts:3,rest:'balanced',seed:4242,skills:new Map(),attempts:120,fixed});expect(r).toBeTruthy();expect(r.requestedCourts).toBe(3);expect(r.effectiveCourts).toBe(2);expect(r.games).toHaveLength(9);});
test('reduced courts preserve fixed history and use non-colliding new round labels',()=>{const s=loadScheduler(),players12=Array.from({length:12},(_,i)=>i+1),base=s.generate(cfg(players12,3,3,{seed:4242})),indexes=[0,4,5,6],fixed=new Map(indexes.map(i=>[i,{teams:base.games[i].teams.map(t=>t.slice()),sitting:(base.games[i].sitting||[]).slice(),court:base.games[i].court,round:Math.floor(i/3)}])),players11=Array.from({length:11},(_,i)=>i+1),r=s.generate({players:players11,per:3,totalGames:9,targets:new Map(players11.map(p=>[p,3])),courts:3,rest:'balanced',seed:4242,skills:new Map(),attempts:120,fixed});expect(r).toBeTruthy();expect(r.effectiveCourts).toBe(2);for(const i of indexes){expect(r.games[i].teams).toEqual(fixed.get(i).teams);expect(r.games[i].court).toBe(fixed.get(i).court);expect(r.games[i].round).toBe(fixed.get(i).round)}const fixedRounds=new Set(indexes.map(i=>fixed.get(i).round));for(let i=0;i<r.games.length;i++)if(!fixed.has(i))expect(fixedRounds.has(r.games[i].round)).toBeFalsy();});
test('infeasible court count is capped by player capacity',()=>{const s=loadScheduler(),players=Array.from({length:7},(_,i)=>i+1),r=s.generate(cfg(players,2,3,{seed:77}));expect(r).toBeTruthy();expect(r.requestedCourts).toBe(2);expect(r.effectiveCourts).toBe(1);});
test('dead end retries with fewer courts and returns no holes',()=>{const s=loadScheduler(),players=Array.from({length:16},(_,i)=>i+1),targets=new Map(players.map(p=>[p,[15,16].includes(p)?0:1])),fixed=new Map([[0,{teams:[[1,2],[3,4]],sitting:[],court:1,round:0}]]),r=s.generate({players,per:1,totalGames:4,targets,courts:4,rest:'balanced',seed:12345,skills:new Map(),fixed});expect(r).toBeTruthy();expect(r.requestedCourts).toBe(4);expect(r.effectiveCourts).toBe(3);expect(r.games).toHaveLength(4);expect(r.games.every(Boolean)).toBeTruthy();});
test('fast fallback remains parallel-safe for large rosters',()=>{const s=loadScheduler(),players=Array.from({length:20},(_,i)=>i+1),r=s.generate(cfg(players,4,4,{seed:9090}));expect(r).toBeTruthy();expect(r.effectiveCourts).toBe(4);expect(slotRoundDisjoint(r.games,r.effectiveCourts)).toBeTruthy();});
test('16-player 4-court generation stays under 300ms for five runs',()=>{const s=loadScheduler(),players=Array.from({length:16},(_,i)=>i+1),times=[];for(const seed of [9000,9001,9002,9003,9004]){const t=performance.now(),r=s.generate(cfg(players,4,6,{seed,attempts:420})),ms=performance.now()-t;expect(r).toBeTruthy();expect(r.effectiveCourts).toBe(4);expect(r.games).toHaveLength(24);expect(ms).toBeLessThan(300);times.push(ms)}console.log('[CRG-STEP2B] '+times.map(x=>x.toFixed(2)+'ms').join(', '));});
